### ISSUE TITLE
Describe the use of the new DIAObject association code

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#10]
_From @drphilmarshall on January 18, 2018 23:18_

This now exists! So we need to use it.

_Copied from original issue: LSSTDESC/DC2_Repo#92_

**Comment by drphilmarshall** [comment]
@SimonKrughoff @DominiqueFouchez Looks like the DC2 cookbook at https://github.com/LSSTDESC/ImageProcessingPipelines/blob/master/doc/DRPCookbook.rst now has some initial guidance on running the `afw.MultiMatch` code to associate DIASources into DIAObjects, but then says we'll need a new Task for this. I guess that means writing a code cell into the Cookbook first. Simon, I guessed that you would be best placed to write this Cookbook snippet, but maybe I am wrong? Great if you or Dominique can suggest a way forward, apologies if this is already happening and I am following the wrong thread :-)

**Comment by DominiqueFouchez** [comment]
True, I have a afw.multimatch recipe from an old stack version. I'll check with Simon if needs update.

**Comment by SimonKrughoff** [comment]
That would be great if you put that in @DominiqueFouchez
