### ISSUE TITLE
forcedPhotCcd needs a dedicated config

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/ImageProcessingPipelines#107]
By default, cModel is used for photometry, which breaks for forcedPhotCcd:
`forcedPhotCcd FATAL: Failed on dataId=DataId(initialdata={'visit': 1502, 'filter': 'z', 'raftName': 'R24', 'detectorName': 'S12', 'detector': 113, 'tract': 2904}, tag=set()): FatalAlgorithmError: CModel forced measurement currently requires the measurement image to have the same Wcs as the reference catalog (this is a temporary limitation).
forcedPhotCcd.references INFO: Getting references in {'tract': 2904, 'patch': '3,1'}
Traceback (most recent call last):
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_base/17.0.1-2-g3e5d191+31/python/lsst/pipe/base/cmdLineTask.py", line 388, in __call__
    result = self.runTask(task, dataRef, kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_base/17.0.1-2-g3e5d191+31/python/lsst/pipe/base/cmdLineTask.py", line 447, in runTask
    return task.runDataRef(dataRef, **kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/meas_base/17.0.1-6-gaad6eea+12/python/lsst/meas/base/forcedPhotImage.py", line 259, in runDataRef
    forcedPhotResult = self.run(measCat, exposure, refCat, refWcs, exposureId=exposureId)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/meas_base/17.0.1-6-gaad6eea+12/python/lsst/meas/base/forcedPhotImage.py", line 290, in run
    self.measurement.run(measCat, exposure, refCat, refWcs, exposureId=exposureId)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/meas_base/17.0.1-6-gaad6eea+12/python/lsst/meas/base/forcedMeasurement.py", line 364, in run
    beginOrder=beginOrder, endOrder=endOrder)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/meas_base/17.0.1-6-gaad6eea+12/python/lsst/meas/base/baseMeasurement.py", line 331, in callMeasure
    self.doMeasurement(plugin, measRecord, *args, **kwds)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/meas_base/17.0.1-6-gaad6eea+12/python/lsst/meas/base/baseMeasurement.py", line 361, in doMeasurement
    plugin.measure(measRecord, *args, **kwds)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/meas_modelfit/17.0.1-3-g7e86b59+22/python/lsst/meas/modelfit/cmodel/cmodelContinued.py", line 105, in measure
    "CModel forced measurement currently requires the measurement image to have the same"
lsst.pex.exceptions.wrappers.FatalAlgorithmError: CModel forced measurement currently requires the measurement image to have the same Wcs as the reference catalog (this is a temporary limitation).
`

**Comment by johannct** [comment]
17e3e6f..a3c8d38

**Comment by johannct** [comment]
It also needs the templates to be added to obs_lsst. @heather999 ?

**Comment by heather999** [comment]
I need more details about what templates are missing in `obs_lsst`, @johannct Is there an email exchange, GitHub issue or Slack discussion where what is needed is explicitly explained?

**Comment by johannct** [comment]
https://lsstc.slack.com/archives/CBE964PR8/p1559477962004100 : this is really all I have. K-T clearly asks that we make an effort to fill all the `''` present in obs_base, and which are expected to be overridden in the telescope obs packages. The one that triggered the discussion is `forcedPhotCcd_metadata` in obs_base/policy/datasets.yaml : 
```
forcedPhotCcd_metadata:
    persistable: PropertySet
    storage: YamlStorage
    python: lsst.daf.base.PropertySet
    tables: raw
    template: ''
```

**Comment by jchiang87** [comment]
I can help with this.  Is there a repo already appropriately set up at NERSC that I can try to run `forcedPhotCcd.py` on?

**Comment by johannct** [comment]
@jchiang87 you should be able to run it on the fresh coadd-v1. `forcedPhotCcd.py ${IN_DIR} -j ${NSLOTS} --rerun ${RERUN} --id visit=${VISIT} --timeout 999999999 -C ${ROOT_SOFTS}/ImageProcessingPipelines/config/forcedPhotCcdConfig.py` in the pipeline. You need the config to switch cModel off

**Comment by johannct** [comment]
There are 29 empty templates in obs_base : deepDiff_metadata, deepDiff_diaSrc, deepDiff_kernelSrc, isr_metadata, runIsr_metadata, ossThumb, flattenedThumb, icSrc, icExpBackground, processCcd_metadata, characterizeImage_metadata, calibrate_metadata, forcedPhotCcd_metadata, forced_src, src, calexpBackground, srcMatch, srcMatchFull, jointcal_wcs, jointcal_photoCalib, photoCalib, donutSrc, qaTableVisit, skyCorr, calexp_camera, transmission_sensor, transmission_atmosphere_fgcm, fgcm_photoCalib, apPipe_metadata, dcrDiff_metadata, dcrDiff_diaSrc, dcrDiff_kernelSrc, brighterFatterKernel, brighterFatterGain, plotBrighterFatterPtc, 

in obs_lsst, the following are *not* provided : isr_metadata, characterizeImage_metadata, calibrate_metadata, forcedPhotCcd_metadata, srcMatchFull, photoCalib, donutSrc, qaTableVisit, transmission_sensor, transmission_atmosphere_fgcm, fgcm_photoCalib.

**Comment by jchiang87** [comment]
I added a template entry to the `dc2/run2.1` branch of `obs_lsst`: https://github.com/lsst/obs_lsst/commit/59208500f65c22f511194281d05d85fc8a1a4b99

**Comment by wmwv** [comment]
I agree with @jchiang87 .  

If we're not using stuff and don't anticipate doing so soon then we shouldn't add it.  E.g., `qaTableVisit` is from `qa_explorer` which is under the `lsst-dm` org rather than `lsst`.  `donutSrc` is similarly not widely used.

In this particular case, I suggest we (by which I mean @jchiang87 ) propose `obs_lsst` defaults for the `*_metadata` entries above and leave the rest blank.

**Comment by RobertLuptonTheGood** [comment]
How does this relate to
	https://jira.lsstcorp.org/browse/DM-19985

**Comment by jchiang87** [comment]
Only tangentially, I think.   I expect that if we want to add some missing templates, e.g., the other `*_metadata` entries, then they *could* be part of the changes in DM-19985.  Though given its title, I'm happy to add them as part of a different ticket when the needs arise.

**Comment by johannct** [comment]
I agree. I listed them here for completion, because K-T on slack clearly claimed that undefined templates in obs_base should be overwritten in the concrete instrument obs packages. But it is hard to do so without a well-defined usage case. So DM should probably provide for reasonable default as intended if instruments cannot easily provide for these.

**Comment by johannct** [comment]
looks like this is solved, as I could run forced photometry on CCD for Run2.2 validation tract 3828 run.
