### ISSUE TITLE
final choice of filters to be used for metacal

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/ImageProcessingPipelines#108]
Following up on https://lsstc.slack.com/archives/CHCP5RA1G/p1559626177002800

**Comment by johannct** [comment]
@esheldon is that correct that it is completely redundant to pass `--id filter=r^i^z` at the command line of `processDeblendedCoaddsMetacalMax.py` and to pass it in the config file  as in `config.filters = ['r', 'i', 'z']`
I was under the impression that providing the `--id filter` was still necessary, which would be a bit unfortunate.

**Comment by esheldon** [comment]
My understanding is that It is required on the command line so the butler knows which bands to load.  That was how Jim told me to use it.

It may be we don't need it in both places, but I'll need guidance on that.

**Comment by johannct** [comment]
Closing for now, as 6mths coadd started with griz setup. Can reopen in the future if needs be.
