### ISSUE TITLE
Failures in calexp processing for run 2.1i w19

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/ImageProcessingPipelines#109]
I am seeing the following trace : 

> 58263 FATAL 2019-05-24T16:04:35.748+0200 singleFrameDriver: Failed on dataId={'visit': 3117, 'run': '3117', 'raftName': 'R01', 'detectorName': 'S10', 'detector': 3, 'snap': 0}: InvalidParameterError: 
  File "src/PsfexPsf.cc", line 235, in virtual std::shared_ptr<lsst::afw::image::Image<double> > lsst::meas::extensions::psfex::PsfexPsf::_doComputeImage(const Point2D&, const lsst::afw::image::Color&, const Poin
t2D&) const
    Only spatial variation (ndim == 2) is supported; saw 0 {0}
lsst::pex::exceptions::InvalidParameterError: 'Only spatial variation (ndim == 2) is supported; saw 0'

> Traceback (most recent call last):
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_base/17.0.1-2-g3e5d191+31/python/lsst/pipe/base/cmdLineTask.py", line 388, in __call__
    result = self.runTask(task, dataRef, kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_base/17.0.1-2-g3e5d191+31/python/lsst/pipe/base/cmdLineTask.py", line 447, in runTask
    return task.runDataRef(dataRef, **kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_drivers/17.0.1-5-g0d47de9/python/lsst/pipe/drivers/singleFrameDriver.py", line 72, in runDataRef
    return self.processCcd.runDataRef(sensorRef)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_base/17.0.1-2-g3e5d191+31/python/lsst/pipe/base/timer.py", line 150, in wrapper
    res = func(self, *args, **keyArgs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_tasks/17.0.1-14-g303e8d74/python/lsst/pipe/tasks/processCcd.py", line 189, in runDataRef
    doUnpersist=False,
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_base/17.0.1-2-g3e5d191+31/python/lsst/pipe/base/timer.py", line 150, in wrapper
    res = func(self, *args, **keyArgs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_tasks/17.0.1-14-g303e8d74/python/lsst/pipe/tasks/characterizeImage.py", line 403, in runDataRef
    background=background,
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_base/17.0.1-2-g3e5d191+31/python/lsst/pipe/base/timer.py", line 150, in wrapper
    res = func(self, *args, **keyArgs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_tasks/17.0.1-14-g303e8d74/python/lsst/pipe/tasks/characterizeImage.py", line 465, in run
    psfSigma = psf.computeShape().getDeterminantRadius()
lsst.pex.exceptions.wrappers.InvalidParameterError: 
  File "src/PsfexPsf.cc", line 235, in virtual std::shared_ptr<lsst::afw::image::Image<double> > lsst::meas::extensions::psfex::PsfexPsf::_doComputeImage(const Point2D&, const lsst::afw::image::Color&, const Point2D&) const
    Only spatial variation (ndim == 2) is supported; saw 0 {0}
lsst::pex::exceptions::InvalidParameterError: 'Only spatial variation (ndim == 2) is supported; saw 0'

The corresponding image follows, and is peculiar as it is almost entirely empty: 
![3117_R01_S10](https://user-images.githubusercontent.com/586081/58879462-02d2bf00-86d6-11e9-8820-bd2a33027df2.png)

**Comment by johannct** [comment]
@villarrealas Can you follow up on this and check whether this is a visit/sensor that should not have been simulated as it lies outside of the instcat footprint?

**Comment by RobertLuptonTheGood** [comment]
I think it failed to find enough PSF stars so the data is bad, but you shouldn't get that message (actually I thought I fixed our PSFex wrapper to handle the constant-PSF case).  What version are you running?

**Comment by johannct** [comment]
@RobertLuptonTheGood  the one in w19, which code or package in particular do you wish the tag for?

**Comment by boutigny** [comment]
And here is a focal plane image of visit 431365 made by @johannct and showing the CCD which have this missing sources problem
![calexp-v00431365](https://user-images.githubusercontent.com/5713323/58879939-10d50f80-86d7-11e9-820e-01e28f5c972b.png)

**Comment by johannct** [comment]
Note that we also see another trace, which seems related : 
> 367727 FATAL 2019-06-01T19:40:31.534+0200 singleFrameDriver: Failed on dataId={'visit': 431365, 'run': '431365', 'raftName': 'R02', 'detectorName': 'S10', 'detector': 12, 'snap': 0}: RuntimeError: No objects passed our cuts for consideration as psf stars
Traceback (most recent call last):
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_base/17.0.1-2-g3e5d191+31/python/lsst/pipe/base/cmdLineTask.py", line 388, in __call__
    result = self.runTask(task, dataRef, kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_base/17.0.1-2-g3e5d191+31/python/lsst/pipe/base/cmdLineTask.py", line 447, in runTask
    return task.runDataRef(dataRef, **kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_drivers/17.0.1-5-g0d47de9/python/lsst/pipe/drivers/singleFrameDriver.py", line 72, in runDataRef
    return self.processCcd.runDataRef(sensorRef)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_base/17.0.1-2-g3e5d191+31/python/lsst/pipe/base/timer.py", line 150, in wrapper
    res = func(self, *args, **keyArgs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_tasks/17.0.1-14-g303e8d74/python/lsst/pipe/tasks/processCcd.py", line 189, in runDataRef
    doUnpersist=False,
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_base/17.0.1-2-g3e5d191+31/python/lsst/pipe/base/timer.py", line 150, in wrapper
    res = func(self, *args, **keyArgs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_tasks/17.0.1-14-g303e8d74/python/lsst/pipe/tasks/characterizeImage.py", line 403, in runDataRef
    background=background,
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_base/17.0.1-2-g3e5d191+31/python/lsst/pipe/base/timer.py", line 150, in wrapper
    res = func(self, *args, **keyArgs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_tasks/17.0.1-14-g303e8d74/python/lsst/pipe/tasks/characterizeImage.py", line 461, in run
    background=background,
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_base/17.0.1-2-g3e5d191+31/python/lsst/pipe/base/timer.py", line 150, in wrapper
    res = func(self, *args, **keyArgs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_tasks/17.0.1-14-g303e8d74/python/lsst/pipe/tasks/characterizeImage.py", line 563, in detectMeasureAndEstimatePsf
    expId=exposureIdInfo.expId)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_base/17.0.1-2-g3e5d191+31/python/lsst/pipe/base/timer.py", line 150, in wrapper
    res = func(self, *args, **keyArgs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_tasks/17.0.1-14-g303e8d74/python/lsst/pipe/tasks/measurePsf.py", line 274, in run
    stars = self.starSelector.run(sourceCat=sources, matches=matches, exposure=exposure)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/meas_algorithms/17.0.1-13-g1d86082b+1/python/lsst/meas/algorithms/sourceSelector.py", line 110, in run
    matches=matches)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/meas_algorithms/17.0.1-13-g1d86082b+1/python/lsst/meas/algorithms/objectSizeStarSelector.py", line 456, in selectSources
    raise RuntimeError("No objects passed our cuts for consideration as psf stars")
RuntimeError: No objects passed our cuts for consideration as psf stars

**Comment by jchiang87** [comment]
This visit, 431365, lies entirely within the DC2 WFD region:
![v431365-u_focalplane](https://user-images.githubusercontent.com/1994473/58897212-a8713880-86ac-11e9-8150-44e40b68d089.png)
I think the problematic sensors just need to be re-simulated.   These sensors can be easily identified by looking at the sizes of the centroid files:
```
[cori19] pwd -P
/global/projecta/projectdirs/lsst/production/DC2_ImSim/Run2.1i/sim/y1-y2-wfd/00385844to00445379/00431365
[cori19] ls -l centroid_431365_R* | sort -r | tail -25
-rw-r-----+ 1 desc lsst 4476424 Apr 29 15:51 centroid_431365_R20_S22_u.txt.gz
-rw-r-----+ 1 desc lsst 4475260 Apr 29 15:51 centroid_431365_R23_S00_u.txt.gz
-rw-r-----+ 1 desc lsst 4468735 Apr 29 15:51 centroid_431365_R20_S01_u.txt.gz
-rw-r-----+ 1 desc lsst 4462863 Apr 29 15:51 centroid_431365_R10_S01_u.txt.gz
-rw-r-----+ 1 desc lsst 4460902 Apr 29 15:51 centroid_431365_R12_S00_u.txt.gz
-rw-r-----+ 1 desc lsst 4441388 Apr 29 15:51 centroid_431365_R10_S21_u.txt.gz
-rw-r-----+ 1 desc lsst 4363349 Apr 29 15:51 centroid_431365_R10_S11_u.txt.gz
-rw-r-----+ 1 desc lsst 1611496 Apr 29 15:51 centroid_431365_R01_S12_u.txt.gz
-rw-r-----+ 1 desc lsst 1594578 Apr 29 15:51 centroid_431365_R01_S22_u.txt.gz
-rw-r-----+ 1 desc lsst 1568532 Apr 29 15:51 centroid_431365_R03_S01_u.txt.gz
-rw-r-----+ 1 desc lsst 1562730 Apr 29 15:51 centroid_431365_R01_S02_u.txt.gz
-rw-r-----+ 1 desc lsst 1516063 Apr 29 15:51 centroid_431365_R03_S02_u.txt.gz
-rw-r-----+ 1 desc lsst 1514332 Apr 29 15:51 centroid_431365_R02_S21_u.txt.gz
-rw-r-----+ 1 desc lsst 1485781 Apr 29 15:51 centroid_431365_R02_S01_u.txt.gz
-rw-r-----+ 1 desc lsst 1477419 Apr 29 15:51 centroid_431365_R02_S02_u.txt.gz
-rw-r-----+ 1 desc lsst 1378211 Apr 29 15:51 centroid_431365_R01_S10_u.txt.gz
-rw-r-----+ 1 desc lsst 1366800 Apr 29 15:51 centroid_431365_R01_S21_u.txt.gz
-rw-r-----+ 1 desc lsst 1349591 Apr 29 15:51 centroid_431365_R01_S01_u.txt.gz
-rw-r-----+ 1 desc lsst 1347297 Apr 29 15:51 centroid_431365_R02_S22_u.txt.gz
-rw-r-----+ 1 desc lsst 1341500 Apr 29 15:51 centroid_431365_R01_S11_u.txt.gz
-rw-r-----+ 1 desc lsst 1319421 Apr 29 15:51 centroid_431365_R02_S10_u.txt.gz
-rw-r-----+ 1 desc lsst 1308990 Apr 29 15:51 centroid_431365_R01_S00_u.txt.gz
-rw-r-----+ 1 desc lsst 1280247 Apr 29 15:51 centroid_431365_R01_S20_u.txt.gz
-rw-r-----+ 1 desc lsst 1269039 Apr 29 15:51 centroid_431365_R02_S20_u.txt.gz
-rw-r-----+ 1 desc lsst 1218102 Apr 29 15:51 centroid_431365_R02_S00_u.txt.gz
[cori19]
```
The flawed sensor-visits are about 1/3 the size of the others.

**Comment by johannct** [comment]
thanks Jim! Still it would be better to understand the root cause as this is not the only instance of that type of failures

**Comment by jchiang87** [comment]
> it would be better to understand the root cause as this is not the only instance of that type of failures

I agree, but aside from the instance catalogs being truncated for some reason, I can't think of any obvious cause of this.  Perhaps it's some strange interaction between two `imsim.py` jobs running on the same sensor-visit and writing to the same disk area?  Maybe @villarrealas has some ideas.

**Comment by jchiang87** [comment]
Just to clarify:  I don't think the instance catalogs themselves are flawed.  I re-simulated sensor `R02_S10` for visit 431365, and the resulting image looks fine, comparable to the other sensor-visits shown in the focal plane mosaic.

**Comment by johannct** [comment]
@heather999 : part of the quality check on y3 can involve simply checking the size of the centroid files, as Jim mentioned

**Comment by villarrealas** [comment]
I spent some time looking over this and was unable to find a satisfactory answer explaining the situation form the logging that we have.

There **was** a notable situation in which two jobs started at once due to a dependency failure, but our understanding was that since checkpoints were being stored as tmp files and then renamed into the proper checkpoints, simply cancelling one run would lead to proper behavior. In fact, some of the other sensors on that focal plane are included in the _exact_ same job that would have been running the sensors that failed.

That being said, it would not be too difficult to resimulate if there is a strong desire to do so. I could pull the requisite instance catalogs over and include them as part of one of the other batches being simulated.

**Comment by johannct** [comment]
They may not need re-simulating, but they should be flagged and should not be transferred/processed

**Comment by jchiang87** [comment]
Here's a plot of the centroid file sizes for the `y1-y2-wfd` data.  The size of each file just depends on the local density of objects on the sky, and so it is independent of band, observing time, etc., and will be roughly the same for all sensor-visits.
![y1-y2-wfd_centroid_file_sizes](https://user-images.githubusercontent.com/1994473/58969764-18df8e80-876d-11e9-8e6d-f2301b5b206d.png)
Based on this distribution, I'd say that any centroid file smaller than 4MB corresponds to an incomplete sensor-visit.   For these data, that's 518 out of the 859586 centroid files for `y1-y2-wfd`.

**Comment by johannct** [comment]
ok this is a small number, but it should not be transferred. Are you able to infer the dataId? I scanned by hand the y3 dataset at NERSC and did not see files smaller than 4GB

**Comment by jchiang87** [comment]
> Are you able to infer the dataId?

Yes, I can do that.  I'll run my notebook on the y3 data and will identify any aberrant files.  (I suspect there won't be any.)  Do you need a file list or set of dataIds for the bad y1-y2-wfd data?

**Comment by heather999** [comment]
We should update the sqlite visit DB (currently `/global/projecta/projectdirs/lsst/production/DC2_ImSim/Run2.1i/sim/sqlite_tracking_v1_2.db` and bump the version to `v1_3` to mark these files as "bad".. Given a list for y1-y2-wfd and y3-wfd I can help do that.  Are we prepared to say that a centroid file < 4 MB is a hard requirement going forward for Run2.1i?  Presumably we are just marking specific files to avoid transferring but the rest of the visit should transferred in these cases?

**Comment by jchiang87** [comment]
>  Are we prepared to say that a centroid file < 4 MB is a hard requirement going forward for Run2.1i?
Presumably we are just marking specific files to avoid transferring but the rest of the visit should transferred in these cases?

I think "yes" to both questions.  I'll post the file lists here once I have them.

**Comment by villarrealas** [comment]
I would say not to change the database version ID (since no functionality is changing in the database), but these files should definitely be marked as "False" for passing quality control. I don't think we need a separate field in order to capture this.

**Comment by jchiang87** [comment]
Here's a json file of a python dictionary with the dataId info corresponding to the flawed sensor-visits:
[y1-y2-wfd_small_centroid_files.txt](https://github.com/LSSTDESC/ImageProcessingPipelines/files/3258433/y1-y2-wfd_small_centroid_files.txt)
and for future reference, here's the code I ran to make that dict:
```
import os
import sys
import glob

def find_small_centroid_files(raw_image_dir, min_size=4e6):
    visit_dirs = sorted(glob.glob(os.path.join(raw_image_dir, '00*', '00*')))
    visits = []
    raftNames = []
    detectorNames = []
    sizes = []
    nvisits = len(visit_dirs)
    for i, visit_dir in enumerate(visit_dirs):
        if i % (nvisits//20) == 0:
            sys.stdout.write('.')
        centroid_files = sorted(glob.glob(os.path.join(visit_dir, 'centroid*')))
        for item in centroid_files:
            size = os.stat(item).st_size
            if size < min_size:
                tokens = os.path.basename(item).split('_')
                visits.append(int(tokens[1]))
                raftNames.append(tokens[2])
                detectorNames.append(tokens[3])
                sizes.append(size)
    return dict(visit=visits, raftName=raftNames, detectorName=detectorNames, size=sizes)

raw_image_dir = '/global/projecta/projectdirs/lsst/production/DC2_ImSim/Run2.1i/sim/y1-y2-wfd'
y1_y2_wfd = find_small_centroid_files(raw_image_dir)
```

**Comment by johannct** [comment]
Ok, so after semi-automatic scanning I confirm that all small centroid sensors resulted in FATAL failures (hence no calexp produced, and safe living afterwards) but for these 
[['418193' ['R43' 'R43' 'R43' 'R43' 'R43'] ['S11' 'S12' 'S20' 'S21' 'S22']]

**Comment by jchiang87** [comment]
I would recommend discarding them.   Their centroid file sizes are all around 1-1.5 MB, so they are missing a large number of objects.  Looking at one of them, `R43_S11`, there seem to be a sufficient number of stars for the calexp to be produced, but there are almost certainly a lot of missing galaxies.

**Comment by cwwalter** [comment]
I'm not sure I saw it above.  Do we actually understand what happened in these cases?

**Comment by johannct** [comment]
@jchiang87 ok will do. But we critically have to safeguard against such a problem, as it was not trivial to spot these....

**Comment by villarrealas** [comment]
@cwwalter There's no direct evidence to what happened in the logs, though it did happen when two imSim runs were happening simultaneously on the same instance catalogs. While there is not any clear reason that it should have had this result, it is possible that multiple accesses to the file system may have caused some strange result.

**Comment by wmwv** [comment]
* We should definitely check that our simulated images are simulated correctly.
* We will also always have real data that causes problems both individual CCD and full visit levels: satellite streaks, thick clouds, etc.  Monitoring, classifying, and understands the reasons for such problems will be a part of real data processing.

**Comment by johannct** [comment]
@villarrealas are you able to make a statement that simultaneous reading occurred in other situations where no failure has been reported?

**Comment by villarrealas** [comment]
@johannct I briefly mentioned it before, but in the same job that contained the failed sensors, there are other sensors that worked without error. It is why I initially ruled out that it could be related to the simultaneous jobs. However, the fact that they have since been resimulated correctly implies it must have been some sort of one-off error that didn't impact all sensors (for some reason).

**Comment by johannct** [comment]
@villarrealas I have a hard time following, sorry. You seemed to imply that it might due to two jobs looking at the same set of input files. I fail to comprehend where re-simulating enters into play.

**Comment by villarrealas** [comment]
So, my understanding is as follows @johannct :

1) Two Singularity containers running imSim were started attempting to both run the exact same set of sensors.
2) One of those Singularity containers was cut off after checkpointing had started, but prior to writing outputs. This should not have interfered with checkpointing.
3) Some of those outputs are missing a significant number of objects, others are not.
4) To confirm that this is not at the instance catalog level @jchiang87 resimmed some detectors as a test and has determined that they look fine.

So we're guessing there's some sort of weird file access interplay going on, but I don't have a good answer to give unfortunately as to what happened.

**Comment by katrinheitmann** [comment]
And as far as I know, this was a one-time error, right? Usually, only one job is running at a time.

On 6/6/19 2:55 PM, Antonio Villarreal wrote:

So, my understanding is as follows @johannct<https://github.com/johannct> :

  1.  Two Singularity containers running imSim were started attempting to both run the exact same set of sensors.
  2.  One of those Singularity containers was cut off after checkpointing had started, but prior to writing outputs. This should not have interfered with checkpointing.
  3.  Some of those outputs are missing a significant number of objects, others are not.
  4.  To confirm that this is not at the instance catalog level @jchiang87<https://github.com/jchiang87> resimmed some detectors as a test and has determined that they look fine.

So we're guessing there's some sort of weird file access interplay going on, but I don't have a good answer to give unfortunately as to what happened.

**Comment by villarrealas** [comment]
Correct. This is definitely a one-time error

**Comment by johannct** [comment]
ok so the set of sensors that were targeted by these 2 concurrent containerized executables is compatible with the list of visits/sensors with small centroids?

**Comment by villarrealas** [comment]
Correct. As far as I can tell, the list of sensors with small centroids were all simmed in the batch with 2 concurrent containerized executables. So presumably if it is not at the instance catalog level, it must have crept in at that step - we just don't have a hard answer as to why.

**Comment by johannct** [comment]
run 7999 also has 5 successful calexps from small centroid sensors : R43 "S11", "S12", "S20", "S21", "S22"

**Comment by johannct** [comment]
Ok so there are several visits with calexps to be removed :

**Comment by heather999** [comment]
I have updated the sqlite3 db (`/global/projecta/projectdirs/lsst/production/DC2_ImSim/Run2.1i/sim/sqlite_tracking_v1_2.db`) to mark specific files that fail this new centroid file size test, using the json file that Jim provided.  As already noted this only impacts a small set of `y1-y2-wfd` files.

**Comment by johannct** [comment]
I removed the small centroid entries in the overlaps table with the following piece of code : 
`#!/usr/bin/env python                                                                                                                                                                                               
                                                                                                                                                                                                                    
import json                                                                                                                                                                                                         
import numpy as np                                                                                                                                                                                                  
import sqlite3                                                                                                                                                                                                      
                                                                                                                                                                                                                    
def raftdet2num(raftName, detectorName):                                                                                                                                                                            
     r0=int(raftName[1])                                                                                                                                                                                            
     r1=int(raftName[2])                                                                                                                                                                                            
     s0=int(detectorName[1])                                                                                                                                                                                        
     s1=int(detectorName[2])                                                                                                                                                                                        
     a=0                                                                                                                                                                                                            
     if r0<2:                                                                                                                                                                                                       
         a=-1                                                                                                                                                                                                       
     elif r0>2:                                                                                                                                                                                                     
         a=1                                                                                                                                                                                                        
     return 9*(4*r0+r1+a) + s0*3+s1                                                                                                                                                                                 
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
tmp=json.load(open('y1-y2-wfd_small_centroid_files.txt'))                                                                                                                                                           
small_centroid=np.array([tmp['visit'],tmp['raftName'],tmp['detectorName']])                                                                                                                                         
                                                                                                                                                                                                                    
db = sqlite3.connect('./rerun/calexp-v1/tracts_mapping.sqlite3')                                                                                                                                                    
db_cursor = db.cursor()                                                                                                                                                                                             
for dataId in small_centroid.T:                                                                                                                                                                                     
     print(dataId)                                                                                                                                                                                                  
     selection = "visit=%s and detector=%d"%(dataId[0],raftdet2num(dataId[1],dataId[2]))                                                                                                                            
     #print("delete from overlaps where %s;"%selection)                                                                                                                                                             
     db_cursor.execute("delete from overlaps where %s;"%selection)                                                                                                                                                  
     db.commit()                                                                                                                                                                                                    
     print(db_cursor.fetchall())                                                                                                                                                                                    
db_cursor.close()                                                                                                                                                                                                   
`
Should we transfer the db to NERSC again?

**Comment by johannct** [comment]
cross linking : issue with abnormal calexps (too few sources) https://github.com/LSSTDESC/ImageProcessingPipelines/issues/109

**Comment by heather999** [comment]
Now that this small set of incomplete sensor visits have been identified in `y1-y2-wfd` - do the calexps for those sensors visits need to be removed from the processed data that has already been produced or is it expected they will be left in and just removed from the tract-visit DB as Johann has already done?

**Comment by johannct** [comment]
IMHO they should be deleted : raw and calexp. Cleaner living...

**Comment by heather999** [comment]
I agree, is it easy enough to remove the calexp?  I would naively remove `calexp-v1/calexp/<MostDespisedSensorVisits>` Is that enough?

**Comment by johannct** [comment]
I guess. We need to decide with @airnandez. It is at CC that this is important anyway

**Comment by airnandez** [comment]
The transfer to NERSC of `.../Run2.1i/w_2019_19-v1/rerun/calexp-v1` is now complete (see [details](https://github.com/LSSTDESC/ImageProcessingPipelines/issues/86#issuecomment-502000921)).

We can now proceed to remove the simulated raw images and corresponding calexps that are not worth keeping, both at NERSC and CC-IN2P3.

**Comment by katrinheitmann** [comment]
Are we sure that the raw simulated images can be already removed? I am wondering if there is a chance that they need to be re-processed at some point?

On 6/14/19 6:34 AM, Fabio Hernandez wrote:

The transfer to NERSC of .../Run2.1i/w_2019_19-v1/rerun/calexp-v1 is now complete (see details<https://github.com/LSSTDESC/ImageProcessingPipelines/issues/86#issuecomment-502000921>).

We can now proceed to remove the simulated raw images and corresponding calexps that are not worth keeping, both at NERSC and CC-IN2P3.

**Comment by johannct** [comment]
you mean re-simulated? The new simulation would then overwrite the current faulty one, no?

**Comment by johannct** [comment]
Based on the snippet of python code below, I built a list of raw and calexp files to be removed
`
import json
import numpy as np

def raftdet2num(raftName, detectorName):
     r0=int(raftName[1])
     r1=int(raftName[2])
     s0=int(detectorName[1])
     s1=int(detectorName[2])
     a=0
     if r0<2:
         a=-1
     elif r0>2:
         a=1
     return 9*(4*r0+r1+a) + s0*3+s1

sc = json.load(open("y1-y2-wfd_small_centroid_files.txt"))
f=open('y1-y2-wfd_small_centroid_files_raw.txt', 'w')
for v,r,s in zip(sc['visit'],sc['raftName'],sc['detectorName']):
    d = raftdet2num(r,s)
    f.write('/sps/lsst/dataproducts/desc/DC2/Run2.1i/w_2019_19-v1/raw/%d/%s/%08d-%s-%s-det%03d-000.fits\n'%(v,r,v,r,s,d))
f.close()

f=open('y1-y2-wfd_small_centroid_files_calexp.txt', 'w')
for v,r,s in zip(sc['visit'],sc['raftName'],sc['detectorName']):
    d = raftdet2num(r,s)
    f.write('/sps/lsst/dataproducts/desc/DC2/Run2.1i/w_2019_19-v1/rerun/calexp-v1/calexp/%08d-*/%s/calexp_%08d-*-%s-%s-det%03d.fits\n'%(v,r,v,r,s,d))
f.close()
`
The 2 files are attached.
[y1-y2-wfd_small_centroid_files_calexp.txt](https://github.com/LSSTDESC/ImageProcessingPipelines/files/3301488/y1-y2-wfd_small_centroid_files_calexp.txt)
[y1-y2-wfd_small_centroid_files_raw.txt](https://github.com/LSSTDESC/ImageProcessingPipelines/files/3301489/y1-y2-wfd_small_centroid_files_raw.txt)

@airnandez Fabio can you deal with the raw files? The paths in the file are the ingest soft link, so you need to do a `rm` that also removes the file it links to.
@heather999 is it of for you to use the code above to do the same at NERSC?
I will deal with the 48 faulty calexps once the dr1b-v1 run is completed : it should not matter but I prefer to not take any risk with the production.

**Comment by johannct** [comment]
I think that we are done here.
