### ISSUE TITLE
Simplify the DIA recipe to re-use the calexps from the static sky processing

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#11]
_From @drphilmarshall on January 18, 2018 23:17_

This is clean-up, post-Twinkles: at first we found that we needed to re-make the calexps before doing the differencing, but this should not be necessary.

_Copied from original issue: LSSTDESC/DC2_Repo#91_

**Comment by drphilmarshall** [comment]
@SimonKrughoff @DominiqueFouchez Circling back around to the DIA parts of the DC2 DRP cookbook. Can you comment on modifying the current (i.e. Twinkles?) DRP pipeline code to use the static sky calexps please? This seems like it should be a straightforward edit to the cookbook followed by a tweak to the Twinkles processing code, but you know better than I do!

**Comment by DominiqueFouchez** [comment]
Yes, straightforward, will be done asap : need a cookbook synchro with current pipeline dev first
