### ISSUE TITLE
add ngmix photometry in addition to metacalibration

### ISSUE THREAD

**Issue by rmandelb** [LSSTDESC/ImageProcessingPipelines#116]
*Summary*: This issue is a request to enable ngmix photometry in addition to running metacalibration in the next production run.

During the validation of the metacalibration (@esheldon ) shear estimates documented in [this notebook](https://github.com/LSSTDESC/DC2-analysis/blob/u/EiffL/metacal_validation/validation/Run_1.2i_metacal_tests.ipynb) from @EiffL , an issue was noticed when comparing i-band forced cmodel photometry against metacalibration photometry, even after requiring that i-band be the reference band.  This can be most easily seen in this plot from Francois:

![image (4)](https://user-images.githubusercontent.com/1454906/60360068-cfb7de80-99a8-11e9-9c19-7eb11bc6c73b.png)

The left and right panels are the same plotted quantities, but the right has a cut requiring galaxy blendedness<0.01, which cleans up the plot somewhat.  There is a population of objects (roughly 5-10% of the sample after some reasonably conservative selection criteria for weak lensing) that has cmodel photometry substantially fainter than metacal photometry, as can also be seen here on the left:

![image (3)](https://user-images.githubusercontent.com/1454906/60360035-b747c400-99a8-11e9-8172-9f77463093d9.png)

Metacal is using simultaneous fit to all bands (or perhaps griz only - but more than just one band) for the photometry, and this may be providing more stable results for faint objects with blendedness>0.01, but still not very high, <0.1.  To further investigate this hypothesis, we'd like to run ngmix photometry, which comes with the following advantages over metacal magnitudes:

- Metacal has to add noise to the images, so the photometry is noisier; ngmix does not.
- The ngmix run would use a bulge+disk model to improve the photometry compared to the Gaussian model used by metacal.

Doing this run would (a) let us investigate further and understand potential issues with cmodel photometry that could affect DC2 projects given that a non-negligible fraction of the galaxy population is affected, (b) provide a more useful/informative report to DM if the issues we're seeing with cmodel vs. metacal fluxes persist for cmodel vs. ngmix.

*For more information*: see discussions in the past few weeks in #desc-dm-metacal slack channel.

Pinging @esheldon @EiffL in case questions arise for them.

**Comment by johannct** [comment]
ok @esheldon can you provide the config change please?

**Comment by johannct** [comment]
@rmandelb do you need apple to apple comparison? These plots were obtained with the DR1b-v1 I presume. Should I rerun metacal with the new config on DR1b-v1 again?

**Comment by esheldon** [comment]
Running the `bulge+disk` fitter requires ngmix `v1.3.1`.

The recommended way to install this is with conda
```
conda install ngmix=1.3.1
# or if you don't have conda forge in your channels
conda install -c conda-forge ngmix=1.3.1
```
That will pull in all the dependencies.

Otherwise if you are managing the dependencies yourself, then ngmix is pure python so you can use setup.py without any trouble
```
git checkout v1.3.1
python setup.py install
```

**Comment by esheldon** [comment]
I'll also be tagging a new version of `meas_extensions_ngmix` to support this, which I will note here as well.

**Comment by esheldon** [comment]
I tagged version `0.9.0` for `meas_extensions_ngmix`

**Comment by esheldon** [comment]
![bd-test](https://user-images.githubusercontent.com/621661/60451931-4ba96500-9bfb-11e9-835f-bba0c2c6e4c0.png)

**Comment by esheldon** [comment]
a test on HSC tract `9615-4,4`

I cut on `i-mag > 24.5` and plotted other bands.  These meet my expectations.

**Comment by esheldon** [comment]
other basic sanity checks, s/g separation

using T vs mag
![T-mag](https://user-images.githubusercontent.com/621661/60452157-eace5c80-9bfb-11e9-840f-5eb1b3e9c91b.png)

Using i mag concentration vs mag
![conc-mag](https://user-images.githubusercontent.com/621661/60452182-fae63c00-9bfb-11e9-99b8-b39620b545bc.png)

**Comment by esheldon** [comment]
what filters do we want to run?

**Comment by esheldon** [comment]
I misinterpreted some of the plots from @EiffL 

please see my posts on the desc-dm-metacal channel

**Comment by johannct** [comment]
this is now in the pipeline, so I close this issue
