### ISSUE TITLE
VisitInfo object has switched Observatory Latitude, Longitude

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/ImageProcessingPipelines#118]
When I read a `VisitInfo` object for a sample Run 2.1i calexp, `getObservatory` returns the longitude and latitude switched as:

-30.2446W, -70.7494N  2663

~I believe this may just be a simple consequence of the similar error in `lsst/sims_skybrightness`:~

~https://github.com/lsst/sims_skybrightness/issues/30~
[Edit: sims_skybrightness is fine.  I can't read when jet-lagged.]

although I didn't think that `sims_skybrightness` was the source of truth we used for the observatory positions.

Reproduce on NERSC with the w_2019_23 weekly CVMFS distribution and
```
from lsst.daf.persistence import Butler

repo = '/global/projecta/projectdirs/lsst/production/DC2_ImSim/Run2.1i/desc_dm_drp/w_2019_19-v1/rerun/calexp-v1'

butler = Butler(repo)
data_id = {'filter': 'r', 'detector': 123, 'visit': 40247, 'raftName': 'R30', 'detectorName': 'S20'}
visit_info = butler.get(datasetType='calexp_visitInfo', dataId=data_id)

print(visit_info.getObservatory())
```

In general I find the following for the visitInfo.  I don't see anything else obviously wrong, (although I do have difficulty thinking about "HourAngle" in radians, it does translate to the correct value).
```
{'getBoresightAirmass': 1.44360887304971,
 'getBoresightAzAlt': SpherePoint(264.701418044488*geom.degrees, 43.8448868393848*geom.degrees),
 'getBoresightHourAngle': 1.34363 rad,
 'getBoresightParAngle': 2.67951 rad,
 'getBoresightRaDec': SpherePoint(64.3982488659768*geom.degrees, -42.5753478405812*geom.degrees),
 'getBoresightRotAngle': 0.140008 rad,
 'getDarkTime': 30.0,
 'getDate': DateTime("2022-02-24T01:12:38.985799942", TAI),
 'getEra': 2.99546 rad,
 'getExposureId': 40247123,
 'getExposureTime': 30.0,
 'getLocalEra': 2.46759 rad,
 'getObservatory': -30.2446W, -70.7494N  2663,
 'getRotType': RotType.SKY,
 'getUt1': nan,
 'getWeather': Weather(nan, nan, 40)}
```

**Comment by wmwv** [comment]
Looking at the raw images (on IN2P3/CC)

In HDU0 of `/sps/lsst/datasets/desc/DC2/Run2.1i/00000000to00071840/00040276/lsst_a_40276_R42_S12_r.fits`

both OBS-LONG and OBS-LAT are -70.74941699999999

Reproduce with
```
/pbs/home/w/wmwv/local/bin/gethead OBS-LONG OBS-LAT /sps/lsst/datasets/desc/DC2/Run2.1i/00000000to00071840/00040276/lsst_a_40276_R42_S12_r.fits
```

**Comment by wmwv** [comment]
The `calexp` based on the above raw have OBS-LONG and OBS-LAT set differently, but backward:

```
/pbs/home/w/wmwv/local/bin/gethead OBS-LONG OBS-LAT /sps/lsst/dataproducts/desc/DC2/Run2.1i/w_2019_19-v1/rerun/calexp-v1/calexp/00040276-r/R42/calexp_00040276-r-R42-S12-det176.fits
-30.244639 -70.749417
```

**Comment by jchiang87** [comment]
This is a bug in `sims_GalSimInterface`:  https://github.com/lsst/sims_GalSimInterface/blob/master/python/lsst/sims/GalSimInterface/galSimDetector.py#L119

**Comment by johannct** [comment]
@jchiang87 @wmwv I presume this has been fix prior to 2.2 start, and can safely be closed?

**Comment by jchiang87** [comment]
Unfortunately, this hasn't been fixed yet.  I'll make a PR now.  For the already generated images, it's just a fix to the header keywords, so it can be done with an afterburner script.

**Comment by johannct** [comment]
ah ok. This needs to be added to @villarrealas 's list of things to do before the transfer then, if not done already.

**Comment by jchiang87** [comment]
It turns out that https://github.com/lsst/sims_GalSimInterface/blob/master/python/lsst/sims/GalSimInterface/galSimDetector.py#L120 is not the underlying cause of the swapped observatory longitude and latitude values in the `VisitInfo` object.  The cause of that problem is this line in `obs_lsst` from before October 28, 2019: https://github.com/lsst/obs_lsst/blob/c763408122a5920b5b050b191c57bffd0a728ed2/python/lsst/obs/lsst/translators/lsst.py#L33

**Comment by cwwalter** [comment]
> The incorrect `OBS-LAT` keyword in `sims_GalSimInterface` is still a bug, but using a version of `obs_lsst` prior to Scott's fix would still have the keyword switch. So we don't really need to run an afterburner on the raw files, but we should use the fix in `obs_lsst`.

Are we already using a late enough version of obs_lsst?

**Comment by jchiang87** [comment]
I don't think so.  The `dc2/run2.2` branch is currently using code from April 18:  https://github.com/lsst/obs_lsst/blob/dc2/run2.2/python/lsst/obs/lsst/translators/lsst.py

**Comment by johannct** [comment]
@heather999 can you cherry pick? Actually we should try to update obs_lsst as much as we can

**Comment by heather999** [comment]
Sure it's possible to cherry pick, I just need to be clear what to pull in. Looking above, I believe I can just grab: lsst/obs_lsst  b9b792a   
https://github.com/LSSTDESC/ImageProcessingPipelines/issues/118#issuecomment-560573330

**Comment by heather999** [comment]
We've set on v19.0.0 which is recent enough that the commit is already included.  The obs_lsst dc2/run2.2 branch has been brought up to date with v19.0.0 and you can see the necessary update here: https://github.com/lsst/obs_lsst/blame/999dc00f53eef00a9981d6b1286016d2592fa0ff/python/lsst/obs/lsst/translators/lsst.py#L33
I think we can consider this done.
