### ISSUE TITLE
there seems to be 676 visits that vanished for coadd stage

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/ImageProcessingPipelines#119]
The dr4 coadd should have used 9271 visits, but querying the tract mapping database seems to only have 8595 visits when querying `sqlite3 rerun/coadd-dr4-v1/tracts_mapping.sqlite3 "select count(distinct visit) from overlaps;"`. There are 9271 calexp directories under rerun, so runtime crashes (that would lead to the tract mapping script not to be run) can hardly explain it

**Comment by heather999** [comment]
Could it be a timeout with sqlite during the writes?

**Comment by johannct** [comment]
I thought I had solved that, but I am going to check. A priori http://srs.slac.stanford.edu/Pipeline-II/exp/LSST-DESC/log.jsp?pi=53478649 tells me that nothing horrendous came out. Remember that now I build a db per visit in scratch space of the worker, then move it to a common sps directory, and only after singleFrameDriver has completed for all the visits do I go back to the produced dbs and do I merge them. As intermediary products the temp dbs are scattered in different directories so I need to check which visits are missing

**Comment by johannct** [comment]
It looks like a silent failure mode in the sqlite3 python package:
