### ISSUE TITLE
In Run 2.1i DR1b: Why are there 169 object_tract_????.hdf5 DPDD Object Tables, but only 153 coadd images?

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/ImageProcessingPipelines#120]
Why are there 169 tracts in Run 2.1i dr1b Object Tables `object_tract_????.hdf5` but only 153 coadd tracts?

```
/pbs/home/w/wmwv(0)>  ls /sps/lsst/dataproducts/desc/DC2/Run2.1i/w_2019_19-v1/dpdd/calexp-v1\:coadd-dr1b-v1/object_table_summary/ | wc --lines
169
```

but only 153 coadd images

```
/pbs/home/w/wmwv(0)> ls -d /sps/lsst/dataproducts/desc/DC2/Run2.1i/w_2019_19-v1/rerun/coadd-v1/deepCoadd/?/???? | cut -d / -f 13 | sort | uniq | wc --lines
153
```

**Comment by johannct** [comment]
@wmwv right now, I do not see how this is possible, can you track which tracts are missing? I hope that this is not a boohoo when cleaning the directory to save space

**Comment by wmwv** [comment]
Oh, wait.  I think I figured it out.  It's about the grizy-band vs. u-band coadds...
The true coadds for DR1b are in 

/sps/lsst/dataproducts/desc/DC2/Run2.1i/w_2019_19-v1/rerun/coadd-dr1b-v1-grizy
/sps/lsst/dataproducts/desc/DC2/Run2.1i/w_2019_19-v1/rerun/coadd-dr1b-v1-u

**Comment by johannct** [comment]
ah ok, but still while would what you were looking for under coadd-dr1b-v1 (whatever it is) be not complete?

**Comment by wmwv** [comment]
What is the intended relationship between

/sps/lsst/dataproducts/desc/DC2/Run2.1i/w_2019_19-v1/rerun/coadd-dr1b-v1-grizy
/sps/lsst/dataproducts/desc/DC2/Run2.1i/w_2019_19-v1/rerun/coadd-dr1b-v1-u

and

/sps/lsst/dataproducts/desc/DC2/Run2.1i/w_2019_19-v1/rerun/coadd-dr1b-v1

**Comment by wmwv** [comment]
Look in those runs, I see 173 coadd tracts with at least one patch image.
```
/pbs/home/w/wmwv(0)> find /sps/lsst/dataproducts/desc/DC2/Run2.1i/w_2019_19-v1/rerun/coadd-dr1b-v1-*/deepCoadd -path '*/?/????/?,?.fits' | cut -f 13 -d / | sort | uniq | wc --lines
173
```

**Comment by johannct** [comment]
too late to investigate. This fell through the cracks
