### ISSUE TITLE
remove INEXACT_PSF from bits_to_cut

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/ImageProcessingPipelines#121]
https://github.com/LSSTDESC/ImageProcessingPipelines/blob/c4ef523f469bfd26a6375d65c8e34f1df3a18648/config/ngmix-deblended-mcalmax.py#L100

INEXACT_PSF seems to be ubiquitous so we should not cut on it

**Comment by johannct** [comment]
https://github.com/LSSTDESC/ImageProcessingPipelines/commit/bc7a88d0f234c9666f17074bc138c47a7b51a2fd
