### ISSUE TITLE
Documenting how to run SRS workflow at CC

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#122]
As discussed at today's meeting planning the next steps for DC2: https://lsstc.slack.com/archives/C77DDKZHR/p1565012161028300
We noted plans to prepare running DM DRP on upcoming 25 sq deg simulation outputs.  There is interest in making sure the knowledge of how to run the SRS workflow at CC is generally available so that other members of DESC DM with CC and SLAC accounts can initiate processing.
Specifically, we would need to know how to submit the the pipeline jobs to SRS from CC (or do you do that from SLAC?) and where at CC it is appropriate to write output.  I would advocate utilizing a distinct DM repo for this validation work.

**Comment by boutigny** [comment]
As far as I know only @johannct knows how run the SRS DESC DM pipeline. This is clearly not a very healthy situation.

**Comment by heather999** [comment]
I know how to run things generally, and I"ve run portions of this SRS workflow at NERSC, but what I do not know is how to specifically start things up at CC.

**Comment by johannct** [comment]
Nothing lives at slac anymore. The only knowledge is to write a proper stream_config.sh and checkpoints.sh in the working dir ( identical to the output directory), and to know how to launch the task from the web interface, using the LOCAL_CONFIG arg to point to the stream_config.sh script with it's proper arfs if necessary. so it actually also requires authorisation to launch tasks from the srs lsst frontend. I will provide a complete example to run coadd when I am back. Are all the calexps transferred to cc?

**Comment by johannct** [comment]
in the works, https://github.com/LSSTDESC/ImageProcessingPipelines/wiki/Running-DRP-at-CC
