### ISSUE TITLE
Trouble running merge_registries.sh at NERSC

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#123]
Ran into three problems:
- Missing space between the end of the contents in the if statements line 17 and 19 and the close bracket: https://github.com/LSSTDESC/ImageProcessingPipelines/blob/848876420006afd8c937c865472ca2e0bada5f8e/workflows/srs/pipe_scripts/merge_registries.sh#L17-L19
- /bin/env is not recognized both on login and batch nodes: 
`/bin/env: bad interpreter: No such file or directory`   
I switched it to `/bin/bash` locally and that worked.
- Missing `fi` between lines https://github.com/LSSTDESC/ImageProcessingPipelines/blob/848876420006afd8c937c865472ca2e0bada5f8e/workflows/srs/pipe_scripts/merge_registries.sh#L20-L21

**Comment by johannct** [comment]
/bon/env not recognized at nersc?

**Comment by heather999** [comment]
I can inquire.. but is indeed unavailable.  I will wait until today's NERSC outage is complete and try again.

**Comment by johannct** [comment]
nah no big deal : it was the only place where I used this struct in the whole IPP..... so mlor on my side. I have a fixed code for the 3 issues, and will test it with ingest at CC of 2.1.1i.
