### ISSUE TITLE
Deal with SLAC https migration

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#127]
Given the recent SLAC move to https.  It looks like our SRS workflow xml files should also make sure to use https where necessary. For example: 
```
http://srs.slac.stanford.edu/Pipeline-II/schemas/2.1/pipeline.xsd">
```
should be `https`. 
https://github.com/LSSTDESC/ImageProcessingPipelines/blob/6d77699e5659b31bf3e494fe7eca91078a17573e/workflows/srs/pipe_setups/DC2DM_DRP.xml#L5

**Comment by johannct** [comment]
done I believe
