### ISSUE TITLE
add script to set up DRP env

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#130]
In addition to the DMstack CVMFS installation, we are also including:

- ngmix
- GCR
- GCRCatalogs
- pyarrow
- meas_extensions_ngmix

While it would be nice to create a single yml and do `conda env  create -f myenv.yml`, that is not currently possible:
 - GCR-catalogs is not available via pypi
- ngmix is conda installable only from `conda-forge` which we avoiding right now to prevent package version mismatches with DMstack versions, 
- meas_extensions_ngmix needs to be cloned from github and setup against the stack

To handle this, a bash script will be used.  
This will be extended to include the ImageProcessingPipelines and DC2-production

**Comment by cwwalter** [comment]
I think previous versions do exist on conda-forge. Matt will need to comment but it might be possible to pin those versions and still get the newer packages like ngmix.

**Comment by heather999** [comment]
We're purposely avoiding conda-forge for now until DM moves to use it for its dependencies. The problem using it now, is that it becomes much harder to pin to DM versions of conda packages if I try to include the conda-forge channel.

**Comment by cwwalter** [comment]
Got it.

**Comment by heather999** [comment]
Done but needs to be updated for current DMstack. Closing this issue and opening another
