### ISSUE TITLE
Record of Run3.0i data transfer campaigns between CC-IN2P3 and NERSC

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#148]
The purpose of this issue is to record the manually-triggered data transfer campaigns between CC-IN2P3 and NERSC for Run3.0i.

Records of previous runs are also available:

- [Run2.2i](https://github.com/LSSTDESC/ImageProcessingPipelines/issues/133)
- [Run2.1i](https://github.com/LSSTDESC/ImageProcessingPipelines/issues/86)
- [Run1.2i](https://github.com/LSSTDESC/ImageProcessingPipelines/issues/89)

**Comment by heather999** [comment]
@airnandez @johannct 
The Run3.0i simulated raw data is now ready to be transferred to CC, stored in `/global/cfs/cdirs/lsst/production/DC2_ImSim/Run3.0i/sim/y*-ddf`
There is a new SQLITE tracking db: `/global/cfs/cdirs/lsst/production/DC2_ImSim/Run3.0i/sim/sqltracking_run3.0i.db`
All FITS files passed fverify and the tracking DB has been updated to note that quality control checks have all passed.

There are 12758 visits in Y01-Y05 as noted in the sqlite tracking db.
Counting the visits by year we see:
Y01: 2751, Y02: 2092, Y03: 2695, Y04: 2366, Y05: 2864 = 12768   
(that difference of 10 is due to some empty directories transferred from Theta)

The data sizes of each directory counting just the FITS files are as follows:
Y01 1.7 TB, Y02: 1.3 TB, Y03: 1.6 TB, Y04: 1.4 TB, Y05: 1.8 TB ~ 7.8 TB total for transfer

Note that there are checkpoint files and centroids in the data directories, but we are assuming you will not copy those.  If you need the centroids, I can modify the estimate.

**Comment by airnandez** [comment]
## [2020-07-02] Run3.0i DRP: NERSC → CC-IN2P3 data transfer campaign

This is the summary of a transfer campaign of  **Run3.0i** simulated images data from NERSC to CC-IN2P3, as requested  [here](https://github.com/LSSTDESC/ImageProcessingPipelines/issues/148#issuecomment-652634259):

| Description  | Value |
| ------------: | :------------ |
| Location at NERSC (sources) | `/global/cfs/cdirs/lsst/production/DC2_ImSim/Run3.0i/sim` |
| Location at CC-IN2P3 (destination) | `/sps/lsst/datasets/desc/DC2/Run3.0i/sim` |
| Number of files transferred  | 440,553 |
| Data volume  |  7.8 TB |

**NOTES:**

* The list of files transferred is located at CC-IN2P3 at `/sps/lsst/datasets/desc/DC2/Run3.0i/logs/2020-07-02-nersc-to-in2p3.txt`.

**Comment by heather999** [comment]
Run3.0i has been superseded by Run3.1i  Closing this issue.

**Comment by airnandez** [comment]
> Run3.0i has been superseded by Run3.1i Closing this issue.

Does this mean that you don't intend to process the 7.6TB of Run3.0i data present at CC-IN2P3 under `/sps/lsst/datasets/desc/DC2/Run3.0i`?

If that is the case, can I remove those data so to recover that storage capacity ?

**Comment by johannct** [comment]
Yes they are flawed. @heather999 @jchiang87 can confirm.

**Comment by heather999** [comment]
Yes Run3.0i was flawed and superseded by Run3.1i. There are no plans to process this data and you can remove Run3.0i from CC. run3.0i is also backed up in HPSS at NERSC just in case we ever have any interest in it or the checkpoint files.

**Comment by airnandez** [comment]
Thanks @heather999, @johannct for your confirmation. **Run3.0i** data will be deleted from CC-IN2P3.

I'm closing this issue.
