### ISSUE TITLE
DC2 Cookbook

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#15]
_From @drphilmarshall on January 9, 2018 23:22_

We have DM pipelines in the form of collections of scripts in various places: for DC2 we will need to pull these together and re-apply to the DC2 images as we make them, starting ASAP. To make sure that we are implementing the data release processing (DRP) pipeline that we want to see, we need a DC2 Cookbook to check against. 

@SimonKrughoff and I discussed this a little, and we decided we should try and write it all down in one DESC Note jupyter notebook. The reasoning is that we might then be able to make it run-nable, which could help with its development. (It's also nice how jupyter makes code blocks easy, you just use a code cell rather than a markdown cell. And GitHub does a nice job of rendering Notebooks so they can be browsed on the DC2 repo web interface.) I can start by copying in the pieces from the Twinkles cookbook ("self-plagiarism is the highest form of self-flattery" - S. Digel). Then we can look through them to check that this is what we want to do. Hope this sounds OK, @katrinheitmann !

I'll assign suitable code reviewers in time, but it'd be great if @jchiang87 @tony-johnson @nicolaschotard and @boutigny could follow along from the beginning, to make sure we are on track. All comments and suggestions welcome!

_Copied from original issue: LSSTDESC/DC2_Repo#73_

**Comment by heather999** [comment]
_From @cwwalter on January 10, 2018 0:30_

We shouldn't forget the repos and scripts that were worked out to do this for DC1. The DIA is of course new here but the static stuff is not.  So gathering that information in will be useful.

**Comment by heather999** [comment]
_From @drphilmarshall on January 10, 2018 0:53_

Absolutely. I originally wrote "pieces from DC1 and Twinkles" but I couldn't find a specific DC1 cookbook recipe (markdown file). I thought the DC1 DM pipeline was derived from the Twinkles static sky recipe (that makes coadds, and objects=coaddsources), so figured that https://github.com/LSSTDESC/Twinkles/blob/master/doc/Cookbook/DM_Level2_Recipe.md would be a good place to start. The additional (or different) steps followed in the DC1 processing will then need to be captured, though - who would be best placed to add those parts?

**Comment by heather999** [comment]
_From @katrinheitmann on January 20, 2018 4:14_

Just a reminder to deliver the first DC2 cookbook version.

**Comment by drphilmarshall** [comment]
@heather999 @nicolaschotard Just checking in on the Cookbook - I'm a bit worried that no-one has contributed to it since [I last touched it on Feb 26](https://github.com/LSSTDESC/ImageProcessingPipelines/commits/master/doc/DRPCookbook.rst), which suggests that it is not being kept up to date with the code development. I was wondering especially how the DIA development was going, so I pinged Simon and Dominique F in issues #9, #10 and #11. Are there other areas where the Cookbook needs bringing up to date with the code, or is everything still too experimental to be documented? I'll try to join for the next TF meeting to listen out for areas where the Cookbook could be usefully updated already - any other suggestions for who I might ask for help would be gratefully received! :-) Thanks!

**Comment by DominiqueFouchez** [comment]
@drphilmarshall @nicolaschotard @heather999 I was in contact with Nicolas few hours ago just about this. I am starting the missing part of the pipeline about DIA dev. I think a synchro between the current pipeline (DRP part) and the cookbook is needed. It's probably good to have a more automatic way to keep the cookbook synchonized with the pipeline. II will discuss more with Nicolas and co, but my idea is to have a "mini/straightforward pipeline" that implement a fixed minimal test of a pipeline sequence, outside a workflow system. BTW, not so far from the RIP cookbook notebook.

**Comment by drphilmarshall** [comment]
Thanks very much, Dominique! I think the big difference between the DRP
pipeline development in DC2 and the Twinkles development in DC1 is that in
DC1 we had the DM expert (Simon) writing the cookbook, and then Tom and
Tony (not so DM-experienced) implementing the code in the workflow engine.
This time we are able to do things the more traditional way: write the code
first, and document it as we go along. As long as we really do keep the
Cookbook up to date, we'll have a good record of what our pipeline is
doing.

I like your idea of a mini-pipeline, that can be run on a single processor
(like a laptop): best of all would be if this could run the _actual DRP
pipeline_ for testing. I know @jchiang87 was thinking for a while about how
to do this, but am not sure how far he got with it - and then parsl came
along.

If we go this way, then maybe the cookbook would be better evolved into a
set of Sphinx-able rst files for readthedocs to display, to document the
pipeline code? If we think this is promising, we can still use the current
cookbook file to collect the information about what is being run and when,
and then refactor it into a Sphinx source later.

**Comment by heather999** [comment]
I think the part I am most concerned about is making sure we settle on some form of documentation - so we can all be contributing to the "official" record. For the time being I'm happy for that to be rST or a notebook, but I'd like it to reside within this repository and accessible by all. if we're moving to a mini-pipeline (using parsl?) then that should reside here too.  In all honesty - we primarily need the content in any form and to determine who is truly on the hook for which sections so we can pester the right people.  Perhaps something to discuss at the Task Force meeting on Monday.
