### ISSUE TITLE
Ask DM Compression Working Group attend future Task Force Meeting

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#16]
Simon mentioned there is a DM Compression Working Group. We are still working to determine what data products and compression will be utilized for DC2.  While we anticipate a new technical note will be written, we would appreciate chatting with this group about their findings.

**Comment by katrinheitmann** [comment]
We have started a DESC note on this (last week): 
https://docs.google.com/document/d/1T5R9yWkZ8xV5c4EmGitDa-nz1XNT3Kkf8BEYGJV3TKg/edit

It's really only a very small start, but will be a good place to collect 
the information. The reason why we put all the data products from all 
stages into one place is that in the end, the DM catalog needs to talk 
to the truth, so it will be good to have the discussion in one place I 
think.

Feel free to add and edit -- I have several additions on my to-do list 
still as well.

**Comment by heather999** [comment]
@katrinheitmann are there any plans to continue with the above DESC note?  I'm inclined to close this issue, as I think the DM processing is producing compressed files for us and now that we know how to slim down the DM DRP repositories to an acceptable size, this is not so pressing.

**Comment by katrinheitmann** [comment]
Since this issue doesn't address the more generic question about the data products we want to keep it makes sense to close it.
