### ISSUE TITLE
Contact HSC about their config and algorithms

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#17]
Simon explained that the config used by HSC is likely the same available in the branch https://github.com/lsst/obs_lsstSim/tree/twinkles_%23435
We should confirm.

**Comment by heather999** [comment]
Is this at all relevant to us @jchiang87?  https://community.lsst.org/t/hsc-defaults-now-require-sky-correction/2631

**Comment by jchiang87** [comment]
It looks relevant.  Given the date of the announcement, I doubt it's been taken into account by us.  The mentioned scripts, e.g., `skyCorrection.py`, certainly does not appear in the DRP cookbook.

**Comment by heather999** [comment]
Yesterday's SSim meeting included a discussion with Bob Armstrong.  Bob will be back in touch to discuss the version of the stack they use on HSC and any suggested updates that are coming soon.  He also indicated we should look to try to use the sky correction mentioned 2 comments above.

**Comment by heather999** [comment]
MWV also mentioned some performance updates that will be available in the next stack weekly (w_2018_14?) https://lsstc.slack.com/archives/C978LTJGN/p1522958729000369

**Comment by heather999** [comment]
We're in closer contact now with those familiar with HSC processing.  Closing this issue.
