### ISSUE TITLE
phosim image transfer between NERSC and IN2P3

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#2]
Prepare for phosim image tranfser between NERSC and IN2P3 Computing Center (CC).  Work out what to use: iRODS, gridFTP transfer, or something else.
Fabio should know whether IN2P3 is already up and running to receive this data (Johann thinks we are still waiting for disk allocation for the whole of DC2 processing).

**Comment by salmanhabib** [comment]
Out of curiosity, can you use Globus for the data transfer? I know there are Globus compatibility  issues with HEP sites but for ASCR computing sites, Globus is the preferred mechanism for automated large-scale data transfers (we have used it for PB/day-scale transfers). On the other hand, if other mechanisms are ok, I do not want to suggest a new idea --

**Comment by TomGlanzman** [comment]
That is, of course, the obvious possibility.  A couple years ago CCIN2P3 
did not support such transfers so we resorted to using iRODS.  We will 
take a fresh look now...

**Comment by airnandez** [comment]
So far we have been using HTTPS for importing the data from NERSC to CC-IN2P3 and that is working well for us: we have observed transfer throughput of ~600 MB/s.

What is difficult in the current situation is that, as far as I understand, at NERSC the namespace under

` /global/projecta/projectdirs/lsst/production/DC2/`

changes often and in a way I don’t quite understand. This makes difficult for me identifying new data present at NERSC that need to be imported to CC-IN2P3. The motivation is that for making things easier for humans, under a top directory specific to DESC data at CC-IN2P3 (namely `/sps/lsst/datasets/desc`) we intend to mimic the namespace of the DESC dataset at NERSC.

I wonder if there is a document where the way you intend to organise the DESC data at NERSC is documented. That would greatly help discovering what new data need to be imported to CC-IN2P3 as they appear at NERSC.

**Comment by airnandez** [comment]
Regarding Globus, we have not a general-purpose Globus endpoint deployed at CC-IN2P3 that we could use for DESC data, in case that would be needed. (To be complete, LHC experiments use dedicated GridFTP end-points.)

So far, we have not experienced problems using standard HTTPS for transfers from NERSC to CC-IN2P3. HTTPS is ubiquitous and much easier to deploy, operate and use than Globus. So unless we encounter issues with HTTPS, we will rather continue using it.

**Comment by johannct** [comment]
Ok so we need the planned file structure under /global/projecta/projectdirs/lsst/production/DC2/ so that we can automatize the transfer.

**Comment by salmanhabib** [comment]
HTTPS is not exactly a high-performance protocol but since the data production rate is not that high anyway and trans-Atlantic BW is limited, looks like it's good enough for now (as long as you get ~TB/hour more or less on a regular basis).

**Comment by TomGlanzman** [comment]
As a point of interest, @airnandez , would it be possible to set up a globus endpoint at CCIN2P3?  It might be worth running some performance tests.

**Comment by kylechard** [comment]
Let me know if you need any help with Globus. Also, if you have an existing GridFTP server we can register that as a Globus endpoint directly (I'm wasn't clear above if you meant the LHC servers are restricted to LHC use or that they don't use the Globus service).

**Comment by airnandez** [comment]
@TomGlanzman I will consider deploying a Globus endpoint at CC-IN2P3 when the data transfer throughput we observe from NERSC (currently ~600 MB/s) starts to limit us. The reason is that, giving the current effort, I want to avoid spending time deploying and operating a new service unless it is absolutely needed.

@kylechard I meant that for LHC traffic we use dedicated GridFTP servers. Those servers use storage and authorisation dedicated to the LHC experiments, so we cannot use them for transferring DESC data. Thanks for offering help with deployment. I take note and will come back to you if/when we decide to deploy Globus for DESC/LSST.

**Comment by johannct** [comment]
for reference the  /global/projecta/projectdirs/lsst/global/DC2 will be the one sync-ed at CC

**Comment by heather999** [comment]
@airnandez Just wanted to alert you to Johann's comment on another issue, asking for a visit file be generated as new data are transferred over: https://github.com/LSSTDESC/ImageProcessingPipelines/issues/6#issuecomment-369625916

**Comment by airnandez** [comment]
I have imported to CC-IN2P3 the files at NERSC located at:

```
/global/projecta/projectdirs/lsst/global/DC2/DC2-phoSim-3_WFD-r
```

At CC-IN2P3 those files are located in:

```
/sps/lsst/datasets/desc/DC2/DC2-phoSim-3_WFD-r
```

**Comment by heather999** [comment]
That is great news @airnandez   Would it be interesting if we provide links to all the Run 1.1p run data? You can choose to transfer it over, or not - but at least it will be available.

**Comment by heather999** [comment]
I'll add symlinks to all data across all bands in the same area at NERSC.  Jim also mentioned we/I could provide you with a script to find dataset covering the same area.  That's on the to do list.

**Comment by airnandez** [comment]
@heather999 If I understand correctly from my conversation with @nicolaschotard , the immediate goal is to transfer to CC-IN2P3 a subset of the data generated at NERSC for the purpose of validating the pipeline with a small dataset. If my understanding is correct, I will trigger the transfer campaign once that small dataset is identified.

**Comment by heather999** [comment]
@airnandez Yes, I believe that is the plan. I will be talking to @jchiang87 - presumably to produce a script where we can locate visits that are covering a similar area of the sky.

**Comment by jchiang87** [comment]
@airnandez I've written a script to set up symlinks in the transfer area noted above.  Here is what's been done:
```
desc@cori17:/global/projecta/projectdirs/lsst/global/DC2> pwd
/global/projecta/projectdirs/lsst/global/DC2
desc@cori17:/global/projecta/projectdirs/lsst/global/DC2> ls
./   DC2-phoSim-3_WFD-g/  DC2-phoSim-3_WFD-r/  DC2-phoSim-3_WFD-y/  find_nearest_visits.py
../  DC2-phoSim-3_WFD-i/  DC2-phoSim-3_WFD-u/  DC2-phoSim-3_WFD-z/
desc@cori17:/global/projecta/projectdirs/lsst/global/DC2> tree | head -20
.
|-- DC2-phoSim-3_WFD-g
|   |-- 000007 -> /global/projecta/projectdirs/lsst/production/DC2/DC2-phoSim-3_WFD-g/output/000007
|   |-- 000027 -> /global/projecta/projectdirs/lsst/production/DC2/DC2-phoSim-3_WFD-g/output/000027
|   |-- 000031 -> /global/projecta/projectdirs/lsst/production/DC2/DC2-phoSim-3_WFD-g/output/000031
|   |-- 000032 -> /global/projecta/projectdirs/lsst/production/DC2/DC2-phoSim-3_WFD-g/output/000032
|   |-- 000035 -> /global/projecta/projectdirs/lsst/production/DC2/DC2-phoSim-3_WFD-g/output/000035
|   |-- 000064 -> /global/projecta/projectdirs/lsst/production/DC2/DC2-phoSim-3_WFD-g/output/000064
|   |-- 000067 -> /global/projecta/projectdirs/lsst/production/DC2/DC2-phoSim-3_WFD-g/output/000067
|   |-- 000075 -> /global/projecta/projectdirs/lsst/production/DC2/DC2-phoSim-3_WFD-g/output/000075
|   |-- 000086 -> /global/projecta/projectdirs/lsst/production/DC2/DC2-phoSim-3_WFD-g/output/000086
|   |-- 000087 -> /global/projecta/projectdirs/lsst/production/DC2/DC2-phoSim-3_WFD-g/output/000087
|   `-- 000090 -> /global/projecta/projectdirs/lsst/production/DC2/DC2-phoSim-3_WFD-g/output/000090
|-- DC2-phoSim-3_WFD-i
|   |-- 000054 -> /global/projecta/projectdirs/lsst/production/DC2/DC2-phoSim-3_WFD-i/output/000054
|   |-- 000058 -> /global/projecta/projectdirs/lsst/production/DC2/DC2-phoSim-3_WFD-i/output/000058
|   |-- 000070 -> /global/projecta/projectdirs/lsst/production/DC2/DC2-phoSim-3_WFD-i/output/000070
|   |-- 000071 -> /global/projecta/projectdirs/lsst/production/DC2/DC2-phoSim-3_WFD-i/output/000071
|   |-- 000077 -> /global/projecta/projectdirs/lsst/production/DC2/DC2-phoSim-3_WFD-i/output/000077
|   |-- 000082 -> /global/projecta/projectdirs/lsst/production/DC2/DC2-phoSim-3_WFD-i/output/000082
desc@cori17:/global/projecta/projectdirs/lsst/global/DC2>
```
The script `find_nearest_visits.py` sorts the simulated visits by distance from the center of the protoDC2 field, places a requirement of at least 90 sensor-visits having been simulated, and makes the symlinks to the top 10 entries in each WFD band in this area.

Let me know if you run into any problems with this set up. Note that I've deleted the previous symlink to the `DC2-phoSim-3_WFD-r` folder.

**Comment by airnandez** [comment]
Thanks @jchiang87 ! Today I imported all the files present at NERSC under 

```
/global/projecta/projectdirs/lsst/global/DC2
```

They are stored at CC-IN2P3 under

```
/sps/lsst/datasets/desc/DC2/Run1.1-test
```

Total: 182611 files, 492 GB.

**Comment by heather999** [comment]
@airnandez @nicolaschotard We discussed starting a transfer of the ongoing Run1.2p data to IN2P3 today at the task force meeting.  The production of that data is ramping up today, and many more visits will likely complete.  We could just provide a link to the full data set, and it will be updated as production continues. Or do you need completed visits identfied?

**Comment by jchiang87** [comment]
@airnandez @nicolaschotard I've added symlinks to Run1.2p data, as before, identifying visits with at least half the focal plane filled and nominally the closest 11 pointings to the protoDC2 center.  I also added the constraint that the pointing offset has to be < 2 deg to help ensure overlap and since Run1.2p isn't as complete in the different bands.  There are ~50 visits linked under the `/global/projecta/projectdirs/lsst/global/DC2/DC2-R1-2p-WFD*` folders.

**Comment by airnandez** [comment]
On 2018-04-18 I imported to CC-IN2P3 all the files available at NERSC under `/global/projecta/projectdirs/lsst/production/DC2/DC2-R1-2p-WFD-*`.

I did not import files under directories  `DC2-R1-2p-uDDF-*` because I assumed those were not needed. At CC-IN2P3, those files are available under `/sps/lsst/datasets/desc/DC2/Run1.2p`.

**Comment by airnandez** [comment]
On 2018-05-28 I transferred to CC-IN2P3 all the files which were present at NERSC under directories:

```
/global/projecta/projectdirs/lsst/production/DC2/DC2-R1-2p-WFD-{g,i,r,u,z,x}/output
```

and had not been previously transferred. At CC-IN2P3 the imported files are stored under:

```
/sps/lsst/datasets/desc/DC2/Run1.2p
```

Files: 155k
Data volume: 0.69 TB

**Comment by TomGlanzman** [comment]
Hi Fabio,

   Out of curiosity, what is the plan for the other half of DC2 Run 
1.2p, i.e., DC2-R1-2p-uDDF-{u,g,r,i,z,y} ?

   Cheers,
    - Tom

**Comment by airnandez** [comment]
## [2018-05-30] Run1.2p DRP: NERSC  → IN2P3 data transfer campaign 

Summary of transfer campaign of data products of Run1.2p from NERSC to IN2P3:

| Description  | Value |
| ------------: | :------------ |
| Location at NERSC (source) | `/global/projecta/projectdirs/lsst/production/DC2` |
| Location at CC-IN2P3 (destination) | `/sps/lsst/datasets/desc/DC2/Run1.2p`|
| Number of files transferred  | 1385514  |
| Data volume transferred  | 3.8 TB  |

The list of files transferred to IN2P3 is located at:

`/sps/lsst/datasets/desc/DC2/Run1.2p/logs/2018-05-30-nersc-to-in2p3.txt`

This campaign includes files present at NERSC under directories:

```
/global/projecta/projectdirs/lsst/production/DC2/DC2-R1-2p-WFD-{u,g,r,i,z,y}
/global/projecta/projectdirs/lsst/production/DC2/DC2-R1-2p-uDDF-{u,g,r,i,z,y}
```

which were not previously transferred to IN2P3.

**Comment by airnandez** [comment]
@TomGlanzman Thanks for clarifying that data under `/global/projecta/projectdirs/lsst/production/DC2/DC2-R1-2p-uDDF-{u,g,r,i,z,y}` also needs to be transferred to IN2P3. That was not obvious to me.

Please see above for details.

**Comment by airnandez** [comment]
## [2018-06-05] Run1.2p DRP: NERSC  → IN2P3 data transfer campaign 

Summary of transfer campaign of data products of Run1.2p from NERSC to IN2P3:

| Description  | Value |
| ------------: | :------------ |
| Location at NERSC (source) | `/global/projecta/projectdirs/lsst/production/DC2` |
| Location at CC-IN2P3 (destination) | `/sps/lsst/datasets/desc/DC2/Run1.2p`|
| Number of files transferred  | 234  |
| Data volume transferred  | 0.763 GB  |

The list of files transferred to IN2P3 is located at:

`/sps/lsst/datasets/desc/DC2/Run1.2p/logs/2018-06-05-nersc-to-in2p3.txt`

This campaign includes files present at NERSC under directories:

```
/global/projecta/projectdirs/lsst/production/DC2/DC2-R1-2p-WFD-{u,g,r,i,z,y}
/global/projecta/projectdirs/lsst/production/DC2/DC2-R1-2p-uDDF-{u,g,r,i,z,y}
```

which were not previously transferred to IN2P3.

**Comment by johannct** [comment]
@airnandez. Should we close this issue, and open another one for DC2, especially in the context of the GPFS AFM framework, which IIUC will automatically map the 2 file systems?

**Comment by airnandez** [comment]
I prefer to leave this issue open until I have confirmed that all the data produced at NERSC are already imported and up-to-date at CC-IN2P3. I will close this issue when I'll be done with that.

Regarding GPFS AFM, I consider that a possible solution for our particular use case, that needs to be verified.

**Comment by airnandez** [comment]
All the files produced at NERSC for Run1.2p are now present at IN2P3.

My understanding is that the simulation campaign for Run1.2p is terminated, so I'm assuming that there won't be more data transfer campaigns from NERSC to IN2P3 for Run1.2p.

This issue will be closed but please feel free to reopen it if you find some discrepancies on the data between NERSC and IN2P3 or if you think we need to transfer additional data to IN2P3.

**Comment by johannct** [comment]
I reopen it to track the new download that will be needed for the reformatted amp files, to be used for the Run1.2 processing.

**Comment by jchiang87** [comment]
@airnandez I've processed the Run1.2p data with the repackaging script to put them in a format for use with `obs_lsstCam`.  There are 12 folders of data at NERSC ready for transfer to IN2P3:
```
[cori03] pwd -P
/global/cscratch1/sd/jchiang8/desc/Run1.2p
[cori03] ls
DC2-R1-2p-WFD-g/  DC2-R1-2p-WFD-u/  DC2-R1-2p-uDDF-g/  DC2-R1-2p-uDDF-u/
DC2-R1-2p-WFD-i/  DC2-R1-2p-WFD-y/  DC2-R1-2p-uDDF-i/  DC2-R1-2p-uDDF-y/
DC2-R1-2p-WFD-r/  DC2-R1-2p-WFD-z/  DC2-R1-2p-uDDF-r/  DC2-R1-2p-uDDF-z/
[cori03]
```

**Comment by jchiang87** [comment]
I've added a `CALIB` folder to the above directory with the bias and dark calibration products constructed from the phosim bias and dark frames.  You should be able to specify the location of this folder with the `--calib` flag for command line tasks like `constructFlat.py` or `processCcd.py`.

**Comment by johannct** [comment]
Calibs products are not to be ingested by ingestCalib.py?

**Comment by jchiang87** [comment]
I just updated the wiki with the procedure: https://github.com/LSSTDESC/ImageProcessingPipelines/wiki/Generating-Calibration-Products

**Comment by airnandez** [comment]
## [2018-07-05] Run1.2p DRP: NERSC  → IN2P3 data transfer campaign 

Summary of transfer campaign of reformatted data of Run1.2p from NERSC to IN2P3:

| Description  | Value |
| ------------: | :------------ |
| Location at NERSC (source) | `/global/cscratch1/sd/jchiang8/desc/Run1.2p` |
| Location at CC-IN2P3 (destination) | `/sps/lsst/datasets/desc/DC2/Run1.2p-newformat`|
| Number of files transferred  | 158557  |
| Data volume transferred  | 3.2 TB  |

Only the FITS files located at NERSC under directories below were transferred:

`/global/cscratch1/sd/jchiang8/desc/Run1.2p/DC2-R1-2p-WFD-{g,i,r,u,y,z}`
`/global/cscratch1/sd/jchiang8/desc/Run1.2p/DC2-R1-2p-uDDF--{g,i,r,u,y,z}`
`/global/cscratch1/sd/jchiang8/desc/Run1.2p/CALIB`

The list of files transferred to IN2P3 is located at:

`/sps/lsst/datasets/desc/DC2/Run1.2p-newformat/logs/2018-07-05-nersc-to-in2p3.txt`

**Comment by jchiang87** [comment]
@airnandez I've repackaged the full set of phosim dome flats into `raw` files that can be used with `constructFlat.py` to make calibration flats to use with the Run1.2p processing.   Those dome flats are all in 
`/global/cscratch1/sd/jchiang8/desc/calibration_products/phosim/dome_flats/rescaled`
Could you please transfer these to CC-IN2P3?

@johannct @boutigny The pixel values in these `raw` files have been rescaled to match the v3.7.9 gains.

**Comment by airnandez** [comment]
@johannct @boutigny Where at IN2P3 under `/sps/lsst/datasets/desc/DC2` would you like we import the dataset mentioned in the previous comments?

This is the current status of that directory:

```
$ tree -L 1 /sps/lsst/datasets/desc/DC2/
/sps/lsst/datasets/desc/DC2/
├── Run1.0
├── Run1.1
├── Run1.2p
└── Run1.2p-newformat

4 directories, 0 files
```

**Comment by airnandez** [comment]
In a conversation via Slack with @johannct and @boutigny, we concluded that these calibration files will be imported at IN2P3 under:

```
/sps/lsst/datasets/desc/DC2/Run1.2p/calib_raw
```

**Comment by airnandez** [comment]
## [2018-09-04] Run1.2p DRP: NERSC  → IN2P3 data transfer campaign 

This is the summary of transfer campaign of raw calibration data of Run1.2p from NERSC to IN2P3, as requested by @jchiang87 [above](
https://github.com/LSSTDESC/ImageProcessingPipelines/issues/2#issuecomment-41821318):

| Description  | Value |
| ------------: | :------------ |
| Location at NERSC (source) | `/global/cscratch1/sd/jchiang8/desc/calibration_products/phosim/dome_flats/rescaled` |
| Location at CC-IN2P3 (destination) | `/sps/lsst/datasets/desc/DC2/Run1.2p/calib_raw`|
| Number of files transferred  | 19467  |
| Data volume transferred  | 2.4 TB  |

The list of files transferred to IN2P3 is located at:

`/sps/lsst/datasets/desc/DC2/Run1.2p/logs/2018-09-04-nersc-to-in2p3.txt`

**Comment by heather999** [comment]
We are done with phosim transfers for Run1.2p, closing this issue
