### ISSUE TITLE
Organize simulated images at NERSC to allow for automated discovery of new data to transfer to CC-IN2P3

### ISSUE THREAD

**Issue by airnandez** [LSSTDESC/ImageProcessingPipelines#23]
This issue was created after a discussion started by e-mail.

The issue: how to discover new simulated data files created at NERSC that need to be transferred to CC-IN2P3 for processing?

The current situation is that relevant data is stored at NERSC at:

` /global/projecta/projectdirs/lsst/production/DC2/`

but the namespace under that directory changes often which makes the discovery of new data difficult.

**Comment by airnandez** [comment]
In the original e-mail thread, @TomGlanzman suggested :

> One suggestion might be to create a new directory, say, `/global/projecta/projectdirs/lsst/global`, that would contain symbolic links to those directories of interest.  In this way, we would have a policy-driven location containing everything of interest. What do you think?

**Comment by airnandez** [comment]
@TomGlanzman Your suggestion of creating symbolic links under a given top directory may work. The same hierarchy would be replicated at CC-IN2P3 (under a different top directory).

I think we must ensure:

- that any file that appears under that top directory at NERSC needs to be transferred to CC-IN2P3
- that only files to be transferred to CC-IN2P3 appear under that top directory

In order to make progress to validate this approach, I suggest we make a test: you create the directories and links at NERSC under a convenient top directory and let me know when ready to trigger the transfer to CC-IN2P3.

**Comment by heather999** [comment]
After conferring with Tom, we now have a new directory /global/projecta/projectdirs/lsst/global/DC2, which contains a starter symlink to the DC2-phoSim-3_WFD-r output.
This might be a good place to start some transfer testing.  Suggestions are welcome :)

**Comment by johannct** [comment]
as per https://github.com/LSSTDESC/ImageProcessingPipelines/issues/2, we can probably close this one?

**Comment by heather999** [comment]
Sounds fine to me!  Please use #2 for further discussion and problems.
