### ISSUE TITLE
Keeping obs_lsstSim fork in operational state for processing

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#25]
We agreed at the Monday Task Force meeting that we would work to keep the forked copy of [obs_lsstSim](https://github.com/LSSTDESC/obs_lsstSim) master branch in an operational state for processing.  This may require syncing with DM's lsst master and merging in branches such as twinkles_435. Whatever steps or discussion necessary to do this can be addressed in this issue.  In the meantime, this issue can also be used to indicate what is the "best" branch of obs_lsstSim to use for development... that seems to be [twinkles_435](https://github.com/LSSTDESC/obs_lsstSim/tree/twinkles_435).

**Comment by heather999** [comment]
Jim confirmed as of Feb 22nd that the configs in master and the twinkles_#435 branch are identical. See Slack: https://lsstc.slack.com/archives/C77DDKZHR/p1519338753000597

**Comment by johannct** [comment]
this is probably a moot issue.
