### ISSUE TITLE
Short term reference catalog for mini DRP pipeline

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#28]

**Comment by heather999** [comment]
There are reported issues with the new reference catalog `/global/projecta/projectdirs/lsst/groups/SSim/DC2/eyeball/reference_repo/ref_cats/` see: https://github.com/LSSTDESC/obs_lsstSim/pull/3
We have an older reference catalog which only include stars: `/global/homes/j/jchiang8/scratch/DC2/phosim_Run1.1p/ref_cat_Run1.1p.txt`
For now, we will use the older reference catalog, while keeping an eye on status of the reference catalog discussions?

**Comment by jchiang87** [comment]
Yes, just use the older one.
