### ISSUE TITLE
identify datasets to exercise mini DRP pipeline

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#30]
For now I'm naively starting with `/global/projecta/projectdirs/lsst/production/DC2/DC2-phoSim-3_WFD-r/output/000004` Is there some combination of bands, # of visits, etc we should be targeting as we get started?  Do we start with just eImages, amplifier images, or look to work with both?

**Comment by jchiang87** [comment]
I would just start with eimages.  Running amplifier images requires calibration data, which as far as I know, do not exist.

**Comment by heather999** [comment]
@nicolaschotard mentioned this very thing again today at the CI meeting.  Adding this comment to keep it in mind.  I gather we are to identify 10 visits per band which cover the same area of the sky.

**Comment by heather999** [comment]
See: https://github.com/LSSTDESC/ImageProcessingPipelines/issues/2#issuecomment-372484075
