### ISSUE TITLE
understanding modern obs_lsstSim configs

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#31]
The local configs directory has been removed from this repo in favor of using the configs in the obs_lsstSim fork:
https://github.com/LSSTDESC/ImageProcessingPipelines/pull/24
We need to understand the updated configs and how to properly use them, particularly for the ingest reference catalog.
Jim has independently confirmed at the configs in the master branch of the fork are currently (as of Feb 22nd) identical to the configs in the twinkles_#435 branch.

**Comment by boutigny** [comment]
The DC1_IngestRefConfig.py config file which was used together with IngestIndexedReferenceTask.py is not there anymore. Should we use IngestIndexedReferenceTask.py instead ? If yes, I am not sre that the line `config.mag_column_list = ['lsst_g', 'lsst_r', 'lsst_i']` is valid.

**Comment by jchiang87** [comment]
That's correct Dominque.  That mag_column_list in IngestIndexedReferenceTask.py should be revised.

**Comment by johannct** [comment]
would that explain Jim's reported execution failure, which ended with something like filter_u not recognized?

**Comment by jchiang87** [comment]
It's possible.  I didn't do the ingest.  I'll see if I can regenerate the fits files with that config updated.

**Comment by johannct** [comment]
@airnandez : holding off the transfer of the complete ref_cat to CC, pending the check above.

**Comment by jchiang87** [comment]
The config that was used seems to have the required column list.   See
```
/global/projecta/projectdirs/lsst/groups/SSim/DC2/eyeball/reference_repo/config/IngestIndexedReferenceTask.py
```

**Comment by boutigny** [comment]
We can still copy the reference txt file

**Comment by johannct** [comment]
@jchiang87 : indeed, albeit with some "_smeared" suffixes

**Comment by boutigny** [comment]
I think that the config file compatible with ref_cat_Run1.1p.txt can be recovered from the old branch :  https://github.com/LSSTDESC/ImageProcessingPipelines/blob/u/jchiang/pegasus_daxgen_files/configs/DC1_IngestRefConfig.py

**Comment by heather999** [comment]
Should we go ahead and recover the older copy of the configs and put them back into master?  I think anything that makes things clear - even if it is a short-term solution, would be helpful.

**Comment by heather999** [comment]
Thanks for the clarification @jchiang87 That's just what I was wondering about.  I'll do that during/after the meeting.

**Comment by heather999** [comment]
PR https://github.com/LSSTDESC/ImageProcessingPipelines/pull/33 opened.. ok to merge?

**Comment by johannct** [comment]
PR #33 was merged. Closing this?

**Comment by johannct** [comment]
closing, as superseded by #52
