### ISSUE TITLE
Estimating Data Volumes

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#34]
@nicolaschotard has started to calculate some data volume estimates of input, output, and the catalog to be ingested into Qserv for the DRP.  Looking for additional information from those with some experience in this area.

**Comment by nicolaschotard** [comment]
The very first full production is now (almost) finished for 66 visits (10145 sensors) of Run1.1. SRS pipeline can be found online [here](http://srs.slac.stanford.edu/Pipeline-II/exp/LSST-DESC/task.jsp?task=51392063). The `output` data directory at CC-IN2P3 is located under `/sps/lsst/dataproducts/desc/DC2/Run1.1-test2/w_2018_14/work/0/`. The total size of this directory, contining all outputs of the DM-stack for this processing session (calexp, coadd, catalogs, etc), has a total size of ~4T. 

If we extrapolate this number using simple cross-mutliplication rule, we can estimate that for the ~2000 visits of Run1.2p (~378000 sensors), we should end up with an output data set of ~150T. 

Knowing that Run1.2p is about 25 sq. deg., and DC2 will be 300 sq. deg., we could guess that ~1.5P of output data will be produced for the full DC2 run.

If we instead use the official number of visits that is supposed to be produced (taken from the DC2 planning document, [here](https://www.overleaf.com/read/jwbjvjnszkzf#/43020815/)), we should have ~27,000 visits produced for the main survey, and ~20,000 for the Ultra-DDF, with a total of ~47,000 visits produced. Using a simple cross-multiplication rule based on what has been produced for the partially-complete 66 visits of Run1.1p, we can estimate the full data volume of DM-stack output data to be of ~3.5P.  

Summary:

- Run1.1p, 66 visits (10145 sensors) -> 4T
- Run1.2p, 2000 visits (~378000 sensors) -> 150T
- Full DC2 -> between 1.5P and 3.5P depending of the estimate method

**Comment by katrinheitmann** [comment]
Thanks Nicolas! Scary numbers ... I suppose the compression is switched 
on? How easy would it be to run some of this with the lossy compression 
and do some tests how much it would hurt us scientifically?

We definitely have to get back to the question what is needed, what can 
be derived etc.

Thanks again, Katrin

**Comment by jchiang87** [comment]
It sounds like these numbers include all of the outputs from the DRP analysis, including data products that we decided that we can omit after the processing has finished.  At the DC2_Repo, this issue
https://github.com/LSSTDESC/DC2_Repo/issues/52
specifies the data products that we want to retain.  We can definitely delete the `icExp` stuff, which is about 1/3 of the data volume.  The warped images were also candidates for removal, though it's less clear how much deleting them will save.   We should try to be more precise about which data products we can delete.   A script to do this would be appropriate, I think.

**Comment by cwwalter** [comment]
@nicolaschotard If you want to see some of the discussion on this topic from the DC1 era you can take a look in the discussion are here:

https://lsstc.slack.com/archives/C2M6H2LAX/p1501867673418744

It might also be interesting to see how similar the break down we see is to the V13 ouputs we got before:

```
cori08:DC1-imsim-dithered % du -sh * | sort -hr
28T     icExp
28T     calexp
21T     deepCoadd
2.0T    src
195G    icSrc
188G    deepCoadd-results
12G     processEimage_metadata
2.6G    srcMatch
838M    eimage
243M    ref_cats_orig
125M    deep_makeCoaddTempExp_metadata
17M     registry.sqlite3
9.9M    background_values
4.9M    deep_assembleCoadd_metadata
620K    config
408K    schema
4.0K    _mapper
0       ref_cats
```

As @jchiang87 says we can get rid of the icExp stuff.  The calexps are needed and the warps he mentioned are in the deepCoadd directory and take up most of the space.  We have talked about keeping a few patches of these on disk and either backing up the rest to tape or regenerating them as needed if it helps with the disk space.  Note everything above was without the compression turned on.

**Comment by heather999** [comment]
I could not help taking a look at the current breakdown, just in the output directory.
```
/sps/lsst/dataproducts/desc/DC2/Run1.1-test2/w_2018_14/work(0)>du -sh 0/output/* |sort -hr
2.0T	0/output/deepCoadd
868G	0/output/deepCoadd-results
746G	0/output/calexp
132G	0/output/forced
129G	0/output/src
6.3G	0/output/jointcal-results
6.1G	0/output/icSrc
637M	0/output/processEimage_metadata
320M	0/output/srcMatch
171M	0/output/deep_safeClipAssembleCoadd_metadata
171M	0/output/deep_makeCoaddTempExp_metadata
162M	0/output/forcedPhotCcd_metadata
132M	0/output/deepCoadd_forced_metadata
67M	0/output/config
800K	0/output/schema
32K	0/output/verify
0	0/output/repositoryCfg.yaml

```

**Comment by cwwalter** [comment]
Interesting that joint cal is there.  I didn't know that was on by default yet.

Also the relative size between deepCoadd and deepCoadd-results is quite different now.

**Comment by boutigny** [comment]
I just checked that the lossless compression is enabled in obs_lsstSim (confirming what Simon said in a Slack discussion).
So for a calexp, the size is 187MB without compression, while it is 77 MB with default compression

**Comment by heather999** [comment]
@boutigny given the discussion during the Data Access meeting today about projected DC2 data volumes - do we want to update this issue with your thoughts today and as Run1.2p estimates become available?

**Comment by boutigny** [comment]
These numbers are still valid. They correspond to the full DM output that we will keep anyway. What I said today at the Data Access task force meeting is that we can certainly also create a minimal set of catalogs for DESC analysis. In order to do so we can start from the deepCoadd-results + forced + src and forget about the calexp and deepCoadd. By also getting ride of the heavy foot prints we can further reduce the size of the catalog. And if someone needs to have access to the pixel we can certainly provide a mechanism to retrieve them within the butler structure.

**Comment by johannct** [comment]
closing as the discussion has come to an end.
