### ISSUE TITLE
Follow DC2 DRP Catalog Use Case Development

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#35]
Discussion has been directed to the #desc-dm Slack channel
[See Google Doc](https://docs.google.com/document/d/1mi3k9HgnQwVDz82yqaWLPUSUK8xJViDzTFNz4Zb7CPg/edit#heading=h.awgulyowkl1e)

**Comment by johannct** [comment]
@heather999 : I think this can be closed.
