### ISSUE TITLE
Random list of small issues or things to do on the pipeline

### ISSUE THREAD

**Issue by nicolaschotard** [LSSTDESC/ImageProcessingPipelines#36]
I list here some issues we have when running the pipeline, or things that we would like to see modified. All items should be "small" things to fix/change.

- [ ] Determine the list of visit/raft for which we actually have data instead on create a script file for each raft on the visits (for processEimage mostly)
- [ ] CPU problem with saturated/large stars (this might need a specific issue)
- [ ] The reaper does not change the status of ended jobs at CC-IN2P3. Jobs killed by CC stay for a way too long time (days...) in a `running` state
- [x] `makeFpSummary` should be put in a separate process, that we will run in parallel to validateDrp for all visits. Indeed, we now run `processEimage` with one job per-raft. 
- [ ]  Find out where this message comes from in the log for each job `Unable to find /global/homes/d/descdm/minidrp/ImageProcessingPipelines/workflows/srs/pipe_setups None although it is seen in the environment`
- [x]  Set OMP_NUM_THREADS=1 for all jobs running at NERSC. From Tony: "Otherwise low level libraries try to use many threads which a) Achieves very little in terms of performance b) Creates too many threads per compute node."

**Comment by johannct** [comment]
about item 3 : we know the root cause, which is indeed that the CC pipeline does not provide the right information to the pipeline for a job being killed on the CC farm ad being the last one scheduled there. @brianv0  and @tony-johnson  know about it, and the fix on the pipeline should be reasonably straightforward.

**Comment by nicolaschotard** [comment]
**Item 3**: What is exactly the fix that has to be done, and on what side? Is it something that we have to fix at CC (on the VM)? Or on the SRS Pipeline side? Maybe @tony-johnson or @brianv0 can comment on that.

**Comment by johannct** [comment]
obsolete
