### ISSUE TITLE
Discussion on first full-production results for 66 Run1.1p visits 

### ISSUE THREAD

**Issue by nicolaschotard** [LSSTDESC/ImageProcessingPipelines#41]
A first full-production (from calexp to forced-photometry on sensor and coadd) has been done for 66 visits of Run1.1p. The corresponding SRS pipeline task can be found online at http://srs.slac.stanford.edu/Pipeline-II/exp/LSST-DESC/task.jsp?task=51392063 Some jobs are still running, but they should be done by the end of the day. The data can be found at CC-IN2P3 under `/sps/lsst/dataproducts/desc/DC2/Run1.1-test2/w_2018_14/work/0/output`. They have been produced using version `w_2018_14` of the DM stack. Please have a look at this data-set and let me know if you see anything that seems wrong to you, or if you find something missing from the catalogs. 

I should add that this production has been done in order to make sure that there isn't any step missing in the pipeline, and that all wanted features can be found in the final catalogs. It will serve as a base for the next production on Run1.2p data, will allow us to make sure that we are using the right configuration files for each step of the production, and is also a good opportunity to perform a first study about our needs on number of jobs, CPU, disk space, etc.

**Comment by johannct** [comment]
this should probably be closed now
