### ISSUE TITLE
Astrometry is failing in some cases

### ISSUE THREAD

**Issue by boutigny** [LSSTDESC/ImageProcessingPipelines#45]
The standard astrometry is failing on some cases. Up to now 2 instances has been detected on a small subset of Run1.2. The corresponding dataid are:
* 'visit': 254349, 'raft': '3,0', 'sensor': '1,1'
* 'visit': 409035, 'filter': 'z', 'raft': '1,1', 'sensor': '2,1'

The first one is pathological in the sense that it falls in a boundary region where galaxies are present only in a small part of the image. It leads to a **FATAL** so the calexp is not produce.

The second one is trickier as it occur in a "normal" region, it does not lead to a FATAL so the calexp is produced and will have a catastrophic effect in the coaddition if it is included.

There are several things to be investigated:
* extend the initial region where the matcher is looking for matches : calibrate.astrometry.matcher.maxMatchDistArcSec=30 insrtead of 3. This is solving the problem for the first failure but it is possibly dangerous for more crowded region
* decrease drastically the value of config.calibrate.astrometry.wcsFitter.maxScatterArcsec to issue a FATAL if the scatter is too large. The problem is to find the right value that will catch up bad fits and will not reject good ones
* use the new matchPessimisticB matcher which will become the default in the stack soon. The problem is that it does not solve the first case and it is using a lot of (~20 GB) memory (probably due to our reference catalog which is too deep)
* ...

**Comment by johannct** [comment]
@boutigny  good for closing?

**Comment by boutigny** [comment]
> @boutigny good for closing?

Yes
