### ISSUE TITLE
Configure SRS to use the cloud-based distribution of the LSST stack for CC-IN2P3 jobs

### ISSUE THREAD

**Issue by airnandez** [LSSTDESC/ImageProcessingPipelines#48]
At CC-IN2P3 we currently use a local installation of the stack under `/sps/lsst/software/lsst_distrib` for DESC jobs submitted for execution at CC-IN2P3 via SRS.

In order to decommission this area, we would like to certify that the cloud-based software distribution available under `/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib` (details: [sw.lsst.eu](https://sw.lsst.eu)) works well for SRS jobs. The file system `/cvmfs/sw.lsst.eu`  is mounted and accessible (in read-only mode) from all the nodes in both login and batch farms at CC-IN2P3.

Could you please configure the jobs submitted via SRS for execution at CC-IN2P3 to use the stack under `/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib`?

**Comment by johannct** [comment]
running stream 4 of DC2DM_2_PROCESS to test.

**Comment by airnandez** [comment]
Was this test successful? Could we consider that the installation of `lsst_distrib` available under `/cvmfs/sw.lsst.eu` is suitable for  for DESC DC2 and close this issue?

**Comment by johannct** [comment]
closing, as this is done.
