### ISSUE TITLE
need to use env var NSLOTS at CC

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/ImageProcessingPipelines#53]
in the xml, we define options lie `-pe multicores 8 -q mc_long' and we need to consistently attribute the corresponding number of cores requested in a driver command line, for instance at https://github.com/LSSTDESC/ImageProcessingPipelines/blob/2080e3bb211ec2eb4f728c6cf01a55a8844c06a2/workflows/srs/pipe_setups/setup_SingleFrameDriver#L29
SGE has an env variable for that : NSLOTS

**Comment by johannct** [comment]
need to check how this translate for NERSC run, @heather999 ?

**Comment by johannct** [comment]
SGE = Sun Grid Engine. It defines its own env variable autolatically for the number of requested cores : NSLOTS

**Comment by heather999** [comment]
so you want to know if I can set parameters for NERSC jobs via env variables?  I'm not certain about setting number of cores via an env variable - I see how to query the system to find out how many cores are in use though.  I can inquire.  In fact, @TomGlanzman might be able to point me in a direction.

**Comment by TomGlanzman** [comment]
Are we talking in the context of the SLAC Pipeline II workflow engine?  If so, then yes, one can specify the number of cores needed in the task .xml file and the value may be an environment variable.  For the DC2 phoSim tasks, the following line appears in the .xml
```
<var name="DC2_NTHREADS">54</var> 
```
and then,
```
<job maxCPU="${MAXCPU_RAYTRACE}" 
	maxMemory="${MAXMEM_RAYTRACE}"
         batchOptions="${BATCH_OPTIONS_K} | ${DC2_PARTITIONK2} | -c ${DC2_NTHREADS}" 
         executable="${DC2_CONFIGDIR}/runRaytrace.sh"
/>
```
In the case of phoSim, one thread runs on one core so the DC2_NTHREADS variable actually specifies the number of cores required.

How this job runs at NERSC also depends on whether it runs 'directly' via the SLURM jobDaemon or 'indirectly' via the Pilot jobDaemon.  The DC2 phoSim tasks all use the Pilot form.

**Comment by johannct** [comment]
done
