### ISSUE TITLE
Note move from MeasureMergedCoaddSourceTask to DeblendCoaddSourcesTask

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#56]
"As of DM-15104 deblending is no longer performed by the MeasureMergedCoaddSourcesTask but instead is executed in the DeblendCoaddSourcesTask, which must be run before MeasureMergedCoaddSourcesTask to generate a catalog of deblended sources."  This is in w_2018_32
[https://community.lsst.org/t/changes-to-multibanddriver/3131](https://community.lsst.org/t/changes-to-multibanddriver/3131)
I don't believe we have a specific config file for MeasureMergedCoaddSourcesTask - is that correct @boutigny?  Do we use the multiBandDriver.py rather than the individual tasks @johannct ?

**Comment by heather999** [comment]
And catching up with Dominique's configs: https://github.com/lsst/obs_lsstCam/tree/u/boutigny/DC2-2018-08-13/config  So for now I think this is best used with w_2018_30.

**Comment by boutigny** [comment]
As far as I know, @johannct is running `multiBandDriver.py`. 
Yesterday I tried to mimic what is in the `HSC` config and we now do have a `mergeCoaddMeasurents.py` config file but it only contains the band ordering. There are also a `mutiBandDeblend.py` which is empty so I think that it is just a place holder. All this is in the `u/boutigny/DC2-2018-08-13` branch of `obs_lsstCam`
We may have to run a couple of tests to make share that everything is consistent.

**Comment by johannct** [comment]
tests are ongoing. Yes I am running multiBandDriver. I presume that someone is going to update it following DM-15104

**Comment by heather999** [comment]
@johannct @boutigny I believe we have the multibandDriver configs already and this issue can be closed?

**Comment by johannct** [comment]
in w13 I read in multiBandDriver.py:
`from lsst.pipe.tasks.multiBand import (DetectCoaddSourcesTask,
                                       MergeDetectionsTask,
                                       DeblendCoaddSourcesTask,
                                       MeasureMergedCoaddSourcesTask,
                                       MergeMeasurementsTask,)
`
so we can close
