### ISSUE TITLE
Set up latest IN2P3 SRS workflow at NERSC for Run1.2p

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#57]
Need to coordinate with @johannct to be sure what is in this github repo reflects the current version of the pipeline so we can install it for running at NERSC.

**Comment by johannct** [comment]
@heather999 Heather can you post a status for reference, so that we can follow the milestones here. Else, better close this issue

**Comment by johannct** [comment]
this is descoped, as far as 1.2 goes.
