### ISSUE TITLE
coaddDriver is effectively not run in parallel

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/ImageProcessingPipelines#58]
the current code runs coaddDrivers with a series of tract/patch pairs as input, while coaddDriver parallelizes patch-level execution within a tract. So effectively we disable its parallelism.
This gets all the way down to the way we are mapping visits into tract/patch, so we also need to rethink this part.
There is an added related issue that we are straining the file system by requiring reading the WCS of all the visits for one filters at each independent execution of coaddDriver.py. We should rather pass to coaddDriver these visits that intersect the tract provided as input : 
`` coaddDriver.py --id a_tract --select_id the_list_of_visits_intersecting_this_tract --cores 32
``

**Comment by rearmstr** [comment]
With regard to @johannct's second point.  There isn't anything useful currently in the stack, but this will be handled in gen3 middleware.  

For HSC, there seems to be a number of people with essentially the same code that puts the bounding boxes for each CCD into a database.  The visits that overlap can then be queried efficiently.  I can post some code if we don't already have something like that.

**Comment by heather999** [comment]
@rearmstr please go ahead and post some code, even if we have something, it wouldn’t hurt to see another example.

**Comment by rearmstr** [comment]
Here is some code from Jim Bosch that would be fairly easy to adapt for DESC.

[add-from-repo.txt](https://github.com/LSSTDESC/ImageProcessingPipelines/files/2316186/add-from-repo.txt)
[get-id-args.txt](https://github.com/LSSTDESC/ImageProcessingPipelines/files/2316187/get-id-args.txt)

**Comment by johannct** [comment]
@rearmstr can you explain me how to use level in butler.subset? Especially is it possible to get the bbox of a visit, rather than a detector? I am referring to the `for dataRef in butler.subset("calexp", **kwds)` loop in `add-from-repo.txt`. Stated otherwise, is it possible to have the overlap between a visit and the tract/patches without looping over the detectors?

**Comment by rearmstr** [comment]
I don't know of a way to get the bbox of a whole visit.  There is very little visit information available.  Maybe we could do something approximate by getting on of the central detectors and using the average size of the focal plane?  If we get a few extra visits that won't matter much.

**Comment by johannct** [comment]
closing this issue, as the current code commits do use the sql database intermediate step.
