### ISSUE TITLE
Clean up of /global/projecta/projectdirs/lsst/global and planning for future IN2P3 transfers

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#59]
We need to take a fresh look at /global/projecta/projectdirs/lsst/global and see how we can better organize it and make sure the contents are usable by the butler.

Proposal: remove /global/projecta/projectdirs/lsst/global/DC2   This should be obsolete

Proposal: clean up Run1.2p transfers to provide one top-level directory i.e. merge in2p3/Run1.2p-Test and in2p3/Run1.2p

We need to provide @airnandez a full list of what contents need to be transferred from IN2P3 to NERSC when processing occurs.  This requires input from @johannct and @boutigny to outline the expected structure of the processing, as well as input from @jchiang87 @SimonKrughoff and @wmwv to be sure we have everything we need to allow the Butler to access the data.

Going forward, it would be helpful to understand how we expect users to access DC2 data.. will we point them to /global/projecta/projectdirs/lsst/global as well as /global/project/projectdirs/lsst/production/DC2?  Provide symlinks under production/DC2 so users have one area to look at?

**Comment by SimonKrughoff** [comment]
This is what I did to make a working repo out of what did get transferred to NERSC:
``` 
> mkdir test_repo                                                                                                                                                                 
> cd test_repo                                                                                                                                                                    
> ln -s /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/080718/calexp                                                                                      
> ln -s /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/080718/config
> ln -s /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/080718/icSrc
> ln -s /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/080718/postISRCCD
> ln -s /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/080718/schema
> ln -s /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/080718/singleFrameDriver_metadata/
> ln -s /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/080718/src
> ln -s /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/080718/srcMatch
> cp /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/registry.sqlite3 .
> echo 'lsst.obs.lsstCam.LsstCamMapper' > _mapper
```

**Comment by johannct** [comment]
@heather999  Is this still relevant?

**Comment by johannct** [comment]
closing now, as it does not seem to be relevant anymore. Feel free to reopen if needed.
