### ISSUE TITLE
Describe use of `ingestImages.py`

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#6]
_From @drphilmarshall on January 24, 2018 21:28_

Noted by @boutigny as a missing part of the cookbook in https://github.com/LSSTDESC/DC2_Repo/blob/issue/73/cookbook/Notebooks/DC2Cookbook.ipynb

@SimonKrughoff is this an easy upgrade?

_Copied from original issue: LSSTDESC/DC2_Repo#122_

**Comment by heather999** [comment]
_From @SimonKrughoff on January 24, 2018 21:33_

I think so, but I think it may be worth reworking the architecture of the cookbook as a whole rather than upgrading piecemeal.

**Comment by heather999** [comment]
_From @drphilmarshall on January 25, 2018 5:54_

I think we are open to good suggestions of that form! We'd need to merge
carefully though (and ipynb is not the easiest to merge, just as a warning).

**Comment by heather999** [comment]
_From @SimonKrughoff on January 25, 2018 18:43_

OK, maybe we should carry out individual updates, and merge as a "big bang" down the road.

**Comment by heather999** [comment]
_From @drphilmarshall on January 25, 2018 23:32_

Sounds good. I can help with any big merges.

**Comment by heather999** [comment]
_From @nicolaschotard on January 26, 2018 7:43_

It might be easier to work on a simple `.md` or `.rst` file instead of a `.ipynb` one. And I support the comment of @SimonKrughoff on the architecture of this documentation by adding that it might enven be better to restart it from scratch and add only up to date parts piece by piece, instead of updating old parts one by one.

**Comment by heather999** [comment]
Looking back at the DC1 workflow, ingestImages.py was avoided due it being slow, rather PhosimImport was used.  Now there is a new ingestDriver.py available:
https://community.lsst.org/t/introducing-ingestdriver-py/2599
It would be great to try this out.

**Comment by RobertLuptonTheGood** [comment]
> Looking back at the DC1 workflow, ingestImages.py was avoided due it being slow

I worked on that speeding that code up so I hope that all is well, but I'm a bit worried that you wrote your own code (with potential subtle problems) rather than forking and fixing the project version.  It's dangerous!

**Comment by heather999** [comment]
I don't claim direct responsibility for DC1 :) but agreed.. I'm hoping that with DC2 we will be using mainstream tools throughout the workflow.  Part of this exercise is to make sure we're cognizant of all the more recent improvements.

**Comment by jchiang87** [comment]
For DC1, it was actually `ingestSimImages.py` that was replaced (I didn't write the replacement), so `ingestDriver.py` won't necessarily help us if we are still forced to use eimages.

**Comment by johannct** [comment]
There is an ingestDriver.py code, is that the one you are referring to @RobertLuptonTheGood ? We tried it at CC-IN2P3, it worked on the command line, but for unknown reason it failed in the pipeline. We still need to investigate that weird behavior.

**Comment by heather999** [comment]
Do you have a pointer to an example of a failure @johannct ? 

Ok.. still catching up @jchiang87, yes indeed it was ingestSimsImages.py - so presumably if we are able to move to amplifier images we can use ingestDriver?  That may seem a daft question - but I'm still learning :)

**Comment by RobertLuptonTheGood** [comment]
If we're using eimages I'd have expected to first make them look like real camera data then run standard scripts.  But I'm not doing the work.

**Comment by jchiang87** [comment]
I don't know off-hand whether ingestDriver.py would serve the purpose or not.   Can you try please?  We have all sorts of amplifier images from Run1.1p that could be used for a test drive.

**Comment by johannct** [comment]
@heather999 I will provide info as soon as I sort out what is going on. In short the usual ingest works, but when I switch to the ingestDriver the pipeline misbehaves and does not produce the output, without any obvious error messages... Baffling, and I now have something of the same sort with Tony's java code that I tried to wrap up in the same task, just changing at the CC the underlying bash script that calls the full ingest command line in each case....

**Comment by heather999** [comment]
I can run ingestDriver.py on amplifier phosim images both at the command line at NERSC and via a SLAC pipeline pilot job on Haswell.  The parameters were kept very simplistic: 
`ingestDriver.py ${OUTPUT_DATA_DIR} ${INPUT_DATA_DIR}/lsst_a_*.fits.gz --mode link --cores 8 --batch-type none --create --output ${OUTPUT_DATA_DIR}`

**Comment by nicolaschotard** [comment]
I also manage to make it work in a job using a command line of this type.

**Comment by heather999** [comment]
Are there any additional parameters when running ingestDriver.py that you would recommend @nicolaschotard ?

**Comment by nicolaschotard** [comment]
Here is the command line I used for `ingestDiver.py`

```ingestDriver.py ${IN_DIR} @${VISIT_FILE} --cores 16 --mode link --output ${IN_DIR}```

where `$IN_DIR` is my input repository and `$VISIT_FILE` is a file containing the list (absolute path) of files to ingest. It is safer to put that in a file instead of putting this list on the command line with a `*.fits.gz` to avoid problem related to long command line.

**Comment by johannct** [comment]
Furthermore we will need something like that when we want to ingest or "mini-drp process" new files that are transferred in a directory that already has previous files..... which by the way points to the utility of having the transfer job of Fabio/Tom to output such an input file as a byproduct.

**Comment by heather999** [comment]
ingestDriver.py offers `--ignore-ingested`  but yes, I should move to use a visit file too!
@johannct, making sure I fully understand your last point, you are hoping the transfer to IN2P3 will produce a visit file (or something like it) that lists all the new data copied over?  So do we need to add this to #2?  Just want to make sure it's noticed..

**Comment by johannct** [comment]
--ignore-ingested means that we would change the actual command line run. If we can avoid that it would be better. Plus processEImage still needs to start with the new files recently ingested.... Yes you can add to the other issue, if there is no counter-argument.

**Comment by johannct** [comment]
this is in prod now, and visit files seem adequate rather than --ignore-ingested. Can be closed

**Comment by johannct** [comment]
closing....
