### ISSUE TITLE
Many u-band exposures getting rejected when making coadds

### ISSUE THREAD

**Issue by rearmstr** [LSSTDESC/ImageProcessingPipelines#65]
@johannct  noticed that many CCDs were being rejected for Run1.2p when making the u-band coadds.  Up to half of the CCDs were being reject in some cases.  The reason was that the PSF residuals were too large in either the size or the ellipticity.   

By default, we try to identify CCDs where the PSF modeling was not good and not include them in the coadd.  We used HSC data to empirically set these thresholds.  For HSC, where there were typically 6 repeated observations one or two bad epochs can really mess things up.

I first looked the size and ellipticity residuals compared to the PSF model for stars on all the DC2 visits.  I found that the u-band visits are quite a bit noisier than the other bands.  Here is a plot from an r-band visit of the size residuals.

![image](https://user-images.githubusercontent.com/1485496/44932415-37b27f80-ad1a-11e8-829b-f0eb8199c83c.png)

The “used size” refers to objects that were used in the fitting and the “res size” are stars that were reserved from the fitting for validation.  These look fine to me, although there is a slightly large tail.  Here is the corresponding plot from a u-band visit:

![image](https://user-images.githubusercontent.com/1485496/44932460-59136b80-ad1a-11e8-8b44-3fff53af8d34.png)

You can see the increased scatter here.  I looked at the number of stars on average for a couple of u-band visits and it corresponds to 20 stars/CCD.  For the other bands it is typically 50-70.  It is difficult to get an accurate model across the CCD with only 20 stars.  For HSC the PSF modeling got increasingly worse below ~20 stars.  This is most certainly contributing to the increased scatter.

I recommend we either turn off rejecting the CCDs at the coadd stage or make the thresholds such that they really only reject catastrophic outliers.

**Comment by johannct** [comment]
setup currently in place to allow for a dedicated u-and config to avoid this problem, which has been validated using rerun 210918
