### ISSUE TITLE
detection parameters

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/ImageProcessingPipelines#66]
discussion in https://github.com/LSSTDESC/DC2-production/issues/259#issuecomment-418959276 may need attention

**Comment by johannct** [comment]
Hi Bob @rearmstr this discussion may need your attention.

**Comment by heather999** [comment]
https://github.com/LSSTDESC/DC2-production/issues/259 is now closed - are there any remaining details that require attention @johannct?

**Comment by johannct** [comment]
dunno, closing.
