### ISSUE TITLE
need to settle on thresholdType=stdev or pixel_stdev

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/ImageProcessingPipelines#68]
see discussion after https://lsstc.slack.com/archives/C978LTJGN/p1537215603000100

**Comment by johannct** [comment]
By comment from Paul Price I infer that DM take on this, at least for DC2, is to modify the default to pixel_stdev, even if it is dangerous to assume knowledge of the variance model (which justifies that the default is not to be changed upstreal at this stage). Is this the correct decision path to follow @rearmstr @RobertLuptonTheGood  ?

**Comment by rearmstr** [comment]
I am fine changing the threshold type, once the variance issues are resolved.  I don't imagine this will have a big impact because this is on only on the visit processing.  We already use pixel_stdev on the coadds.

**Comment by johannct** [comment]
right so "variance issues" pertains to the imsim part of the problem. @boutigny and @rhl endeavours showed that the situation is fine for the phosim part, once pixel_stdev is selected.

**Comment by RobertLuptonTheGood** [comment]
I don't think that Paul or I speak for DM.  The problem that `pixel_stdev` addresses is the strong vignetting at the edge of the field, and I personally think that it's a fine solution;  @rearmstr's comment makes me a bit happier.
I do not think that there's any other reason to force us to make this change (the excess variance in the calibration products is resolved, and wouldn't be a function of position).
