### ISSUE TITLE
Move to making absolute skymaps with `makeSkyMap.py`

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#7]
_From @drphilmarshall on January 24, 2018 21:26_

In #79 @nicolaschotard writes:

> the sky map that we will make should be absolute (using makeSkyMap.py and the appropriate configuration, e.g. for a ring sky map as for HSC and now CFHT reprocessing) instead of relative to the field (with makeDiscreteSkyMap.py). It would ensure that the sky map won't depend on the list of input visits, and thus on the time and place the reprocessing happens.

Issuing this as a needed edit to the cookbook in https://github.com/LSSTDESC/DC2_Repo/blob/issue/73/cookbook/Notebooks/DC2Cookbook.ipynb

Nicolas, would you be willing to take this on, please? Thanks!

_Copied from original issue: LSSTDESC/DC2_Repo#121_

**Comment by heather999** [comment]
_From @drphilmarshall on January 25, 2018 15:48_

Thanks for the contribution, @nicolaschotard ! I made review comments in PR #124 , cc-ing Jim for comment. Now that you have merged into the main dev branch you or he can make those edits more directly. Can you report to this thread when they are done, so I can then close this out? Thanks! :-)

**Comment by nicolaschotard** [comment]
This has been done a while ago and is already available in the first real data production for 66 visits of Run1.1p. [Here](http://srs.slac.stanford.edu/Pipeline-II/exp/LSST-DESC/task.jsp?task=51392063) for tasks on the SRS web interface, and under `/sps/lsst/dataproducts/desc/DC2/Run1.1-test2/w_2018_14/work/0` for the output data at CC-IN2P3.

**Comment by johannct** [comment]
looks like the cookbook has not been updated though. Do we branch when editing the cookbook as well?

**Comment by johannct** [comment]
Not sure the cookbook is a target anymore...... But anyway this does not need to capture that we let it slip way out of sync
