### ISSUE TITLE
things to fix for next 1.2p reprocessing

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/ImageProcessingPipelines#70]
1. fix the calibration (more darks)
  - The 10 bias and dark raw files have been simulated with the same seed, and thus are actual identicals **TO DO**
  - The dome-flats have been produced with different seeds, but with phosim ~v3.7.15 so they need gains to be rescaled to match version v3.7.9. This has been applied already. **DONE**
  - We are still verifying that the hypothesis that some sensor-to-sensor variations of sky level in visits that gather simulated sensors from both phosim v3.7.9 and v3.7.14 is due again to this change of phosim version. **TO DO**

2. fix the missing deblending of large object when pixel_stdev is used
   - decision is to keep pixel_stdev and set back maxFootprintArea to HSC value of 10000 **DONE**

3. Post-Calexp validation
    - check the naming convention for flux/instFlux and FluxSigma/FluxErr : checkCcdAstrometry needs update **DONE IN IPP?**
   - do we want to run makeFpSummary at CC?
   - do we continue to discard sensors failing checkCcdAstrometry?

4. update to obs_lsst(Cam) master and check the status of pipe_tasks in the used weekly
    -- `cat lsst.obs.lsst.phosim.PhosimMapper > _mapper`  **OK**
    -- pipe_tasks likely to stay as a local version, branch  `u/rearmstr/desc-ccd-fix_w39` **OK**
    -- branch `dc2/run1.2-v2 branch` for obs_lsstCam  **OK**

5. investigate the astrometry failure in the 2 sensors that show up for p and not for i
- throw jointcal in
    -- Accroding @boutigny (see https://github.com/LSSTDESC/DC2-production/issues/275) this might be too much for now **NO JOINTCAL FOR 1.2p**

6. solve deepCoadd-/_results oddity

7. Configuration : 
   -- remove obsolete makeSkyMapConfig.py (which has the wrong pixelScale) : done in https://github.com/LSSTDESC/ImageProcessingPipelines/commit/95561c7d8ec8a9ad134f5e45235e0eb3b0dd9539

**Comment by heather999** [comment]
Hi @johannct for point number 1, the new set of 10 darks that Dominique ingested is enough?  I just want to make sure there is no problem.  Now it is a matter of setting up the reprocessing to use them - right?

**Comment by RobertLuptonTheGood** [comment]
Just to clarify, I had to get some bug fixes onto `w_2018_39`, not that I used bleeding-edge features.  I am not happy that this was necessary!

**Comment by johannct** [comment]
for w39 I would like to know if the pipe_tasks fix that Bob had to put in for sensor naming convention is in. Else I would very much like a weekly with that in, if t ll possible.

**Comment by johannct** [comment]
> Hi @johannct for point number 1, the new set of 10 darks that Dominique ingested is enough? I just want to make sure there is no problem. Now it is a matter of setting up the reprocessing to use them - right?

yes, it is the main reason behind the next reprocessing of 1.2p. I am currently writing a pipeline to set the complete calibration up.

**Comment by heather999** [comment]
@johannct Are there still changes for the tract visit mapping that need to be pushed to this repo?

**Comment by johannct** [comment]
> @johannct Are there still changes for the tract visit mapping that need to be pushed to this repo?

No, I think I committed to master everything a few days ago.

**Comment by johannct** [comment]
si there something to investigate about phosim PSF ellipticity? See https://docs.google.com/presentation/d/1zKTt3xhNkwEUovfF_7AAEEvkZHt65pkoXJ61LyqDhvs/edit#slide=id.g42694ae5da_10_23 ?

**Comment by rmandelb** [comment]
@johannct - that's not a processing problem, it's a potential problem with the actual PSF (i.e., we don't see a sign that the PSF model is a poor description of the stars, but rather that the PSF and stars are more elliptical than we expect).  So that's more of a simulation validation issue than a processing issue.

**Comment by johannct** [comment]
@rmandelb ok, thanks for the feedback!

**Comment by heather999** [comment]
We may be finished with 1.2p, and I think all of the above issues have been handled.  Is it ok to close this @johannct ?
