### ISSUE TITLE
Standardize Processing Naming Convention

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#76]
We need a standardized naming convention for the DM-DC2 processing repositories.  Each reprocessing is identified using the DM stack version used for the processing, i.e. `w_2018_39`. The subdirectory structure includes the `rerun` area that contains the output data. Actual processing may entail multiple versions of calexps, coadds, multiband, etc, but what is released to users will be one final version for each reprocessing.  So, while the `rerun` area may contain `rerun/multiband-v1`, `rerun/multiband-v2`, the final "good" multiband processing needs to be referred to using a standard name, such as `rerun/multiband`.

**Comment by heather999** [comment]
One proposal: we could use symlinks to point to the final version of the output data for each reprocessing, such as `rerun/multiband`=>`rerun/multiband-v2` This will provide a consist interface for users and their notebooks. I have tested this already at NERSC, and our DC2-analysis notebooks work just fine when referring to the symlink.

**Comment by johannct** [comment]
superseded by https://github.com/LSSTDESC/ImageProcessingPipelines/issues/93#issuecomment-500538293
