### ISSUE TITLE
How to Connect DDRP Data to DESC-user advertised names as defined by the Data-Access group

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#78]
The Data Access group has proposed a naming convention for Run1.2i:
"Run_1.2i_alpha"  Original processing of full visits using w_2018_39
"Run_1.2i"   Complete processing using w_2018_39
"Run_1.2i_jointcal" Upcoming reprocessing using a later DMstack with more full featured jointcal

This is just one example, but we need to connect our DDRP data outputs to the DESC-user identifiers for this data.

**Comment by heather999** [comment]
Two suggestions:
1. Once we have identified the DESC-user name for the a particular processing, we should symlink or rename the upper level directory to use that name, i.e. `Run1.2i` => `Run1.2i_alpha`.  Preferably this would occur at the site where the processing occurred before transfer.
1. We need to set up a series of confluence pages that adequately describe each reprocessing for posterity. This should include the actual location of the data, as well as the DESC-user identifier, and all details about the reprocessing.

**Comment by johannct** [comment]
obsolete
