### ISSUE TITLE
Requested Run2.1i Visits for makeFpSummary processing

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#79]
Now that the corrupted Run2.1i files have been moved and labelled "corrupted" (https://lsstc.slack.com/archives/C77DDKZHR/p1546623270107400), a fresh ingest of the existing data has been completed (`/global/cscratch1/descdm/DC2/Run2.1i/w_2018_48`)

As discussed at the 4 Jan 2019 DC2 mtg, we will process a subset of this data through makeFpSummary for the exposure checker.  We need a list of visits.  Who do we tag to help make that happen @jchiang87 @fjaviersanchez @kadrlica ?

**Comment by heather999** [comment]
The five requested visits have been processed and the output is now available at: `/global/cscratch1/sd/descdm/DC2/Run2.1i/w_2018_49/rerun/minidrp`
https://lsstc.slack.com/archives/C932BQ550/p1547129115084000?thread_ts=1546619822.012300&cid=C932BQ550

**Comment by kadrlica** [comment]
Thanks, they've been ingested into the exposure checker.

**Comment by heather999** [comment]
This is finished, closing
