### ISSUE TITLE
Run 1.2p v4 : rerun calexp-v4:coadd-v4

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/ImageProcessingPipelines#80]
After discovering that v3 reprocessing had xtalk disabled incorrectly, v4 has been launched, with calexp done : 
http://srs.slac.stanford.edu/Pipeline-II/exp/LSST-DESC/process.jsp?min=&max=&status=&streamIdFilter=1%5C.&dateCategory=createdate&minDateDate=None&minDate=-1&maxDateDate=None&maxDate=-1&processhours=&submit=Filter&process=52452314&pstream=&process=52452314

The 2 failed runs are due to db locked, and the corresponding step has been rerun manually successfully (this is the visit to tract/patch mapping step).

No astrometry failure, clear indication in the logs that xtalk is been corrected for.

**Comment by johannct** [comment]
coadds are launched, with the filter order grizyu to avoid the failure reported elsewhere due to config difference between u band and the other filters (reminder : if u band job writes the config first on disk, then grizy jobs failed against it. But the reverse is not true).

http://srs.slac.stanford.edu/Pipeline-II/exp/LSST-DESC/process.jsp?min=&max=&status=&streamIdFilter=2%5C.&dateCategory=createdate&minDateDate=None&minDate=-1&maxDateDate=None&maxDate=-1&processhours=&submit=Filter&process=52452305&pstream=&process=52452305

**Comment by johannct** [comment]
coadds are launched, with the filter order grizyu to avoid the failure reported elsewhere due to config difference between u band and the other filters (reminder : if u band job writes the config first on disk, then grizy jobs failed against it. But the reverse is not true).

http://srs.slac.stanford.edu/Pipeline-II/exp/LSST-DESC/process.jsp?min=&max=&status=&streamIdFilter=2%5C.&dateCategory=createdate&minDateDate=None&minDate=-1&maxDateDate=None&maxDate=-1&processhours=&submit=Filter&process=52452305&pstream=&process=52452305

**Comment by johannct** [comment]
6 new failures : 152,159,167,174,179,194

**Comment by johannct** [comment]
on strange trace on stream id 100:

**Comment by johannct** [comment]
63, 124 failed a second time

**Comment by johannct** [comment]
http://srs.slac.stanford.edu/Pipeline-II/exp/LSST-DESC/task.jsp?refreshRate=60&task=52452299&refreshIsOn=true&refreshCount=0 : run completed.
RERUN directories to be transferred are /sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_39/rerun/calexp-v4/ and /sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_39/rerun/coadd-v4/ together with the usual ancillary files.

**Comment by airnandez** [comment]
## [2019-01-22] Run1.2p DRP: IN2P3 → NERSC data transfer campaign 

This is the summary of a transfer campaign of data products of Run1.2p from IN2P3 to NERSC. It was requested by @johannct 

| Description  | Value |
| ------------: | :------------ |
| Location at CC-IN2P3 (sources) | `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_39/rerun/{calexp-v4,coadd-v4}`,`/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_39/{CALIB,ref_cats,registry.sqlite3,_mapper}`|
| Location at NERSC (destination) | `/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_39` |
| Number of files transferred  | 1,655,881 |
| Data volume transferred  | 70 TB |

The list of transferred files is located at NERSC at:

`/global/projecta/projectdirs/lsst/global/in2p3/Run1.2i/logs/2019-01-22-in2p3-to-nersc.txt`

**Comment by wmwv** [comment]
@airnandez 

The NERSC version of `rerun/calexp-v4/repositoryCfg.yaml` has a `_root` that points to an `/sps` directory.  This should be updated to just be `../..` as it is in `rerun/coadd-v4/repositoryCfg.yaml`

E.g.,
```
$ cat /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_39/rerun/calexp-v4/repositoryCfg.yaml
!RepositoryCfg_v1
_mapper: &id001 !!python/name:lsst.obs.lsst.phosim.PhosimMapper ''
_mapperArgs: {}
_parents:
- !RepositoryCfg_v1
  _mapper: *id001
  _mapperArgs: {}
  _parents: []
  _policy: null
  _root: /sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_39
  dirty: true
_policy: null
_root: null
dirty: true
```

The `_root:` should instead be `../..`

**Comment by airnandez** [comment]
Thanks @wmwv  for this notification. I modified the contents of the file at NERSC:

```
$ cat /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_39/rerun/calexp-v4/repositoryCfg.yaml
!RepositoryCfg_v1
_mapper: &id001 !!python/name:lsst.obs.lsst.phosim.PhosimMapper ''
_mapperArgs: {}
_parents:
- !RepositoryCfg_v1
  _mapper: *id001
  _mapperArgs: {}
  _parents: []
  _policy: null
  _root: ../..
  dirty: true
_policy: null
_root: null
dirty: true
```

I had understood that the `repositoryCfg.yaml` was now created using a relative path as value of the `_root` key. I strongly prefer not to add intelligence to the data transfer procedure for modifying the contents of the files to be transferred.

I propose that we use relative paths that work both at NERSC and CC-IN2P3. @johannct is this possible? Would you like we create a separate issue to handle that?

**Comment by johannct** [comment]
I forgot to fix one of the repositoryCfg.yaml file it seems. This needs to be fixed in the pipeline unfortunately, the yaml file will not be *created* with relative path, as it is bound to disappear with gen3 anyway. So it has to be dealt with after calexp processing has been launched

**Comment by johannct** [comment]
http://srs.slac.stanford.edu/Pipeline-II/exp/LSST-DESC/task.jsp?refreshRate=60&task=52452299&refreshIsOn=true&refreshCount=0 : run completed.
RERUN directories to be transferred are /sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_39/rerun/calexp-v4/ and /sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_39/rerun/coadd-v4/ together with the usual ancillary files.
