### ISSUE TITLE
Brighter-Fatter kernel generation pipeline task

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/ImageProcessingPipelines#82]
We need an SRS pipeline task that will run the `makeBrighterFatterKernel.py` pipe-task from the [cp_pipe](https://github.com/lsst/cp_pipe) package.  In the DC2-production repo there is an [example script](https://github.com/LSSTDESC/DC2-production/blob/d793b9567f872993b700e1afc00f39ea786797b2/scripts/test_bf.sh) that shows the necessary steps, including how to incorporate the resulting data products into single frame processing.  (Note that some of info in that script is out-of-date.)  As inputs, we'll need appropriate BF flats, which will be generated by a separate SRS pipeline task.

**Comment by heather999** [comment]
@TomGlanzman and I have set up a DMstack w_2018_49 + obs_lsst branch u/jchiang/run2.xi_stars_only_ref_cats and have successfully run a slightly modified version of the example script above.  This entailed copying some data back over from NCSA (lsst-dev) and providing a full path to the `makeBrighterFatterKernel.py` script, as it does seem to be added to the path automatically.  The output was then run through the tail end (starting from cell 27) of Michael's jupyter notebook, original here: https://github.com/LSSTDESC/DC2-production/blob/u/wmwv/bf_kernel/Notebooks/make_brighter_fatter_kernel.ipynb

Next we will run the bf kernel generation with Run1.2i calibrations available.

![bf__kernel_nocalib1](https://user-images.githubusercontent.com/10982136/52567289-f0a4dc00-2dd9-11e9-99ed-d22c80ecfd24.png)
![bf_kernel_nocalib2](https://user-images.githubusercontent.com/10982136/52567288-f0a4dc00-2dd9-11e9-8b72-eeb611c591f7.png)

**Comment by heather999** [comment]
I made an initial attempt at running the code with the Run1.2i calibrations and setting some configs to use them.  
Trying: 
`STACKCVMFS/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/cp_pipe/16.0-4-gade8416+10/bin/makeBrighterFatterKernel.py "${LSSTCAM_REPO_DIR}" --rerun test --id detector=0..3 --visit-pairs 161899,161900 -c xcorrCheckRejectLevel=2 doCalcGains=False isr.doDark=True isr.doBias=True isr.doCrosstalk=True isr.doDefect=True isr.doLinearize=True --clobber-config --clobber-versions`


`makeBrighterFatterKernel FATAL: Failed on dataId={'detector': 3, 'raftName': 'R01', 'detectorName': 'S10', 'visit': 161899}: AttributeError: 'ImsimMapper' object has no attribute 'map_linearizer'
Traceback (most recent call last):
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/pipe_base/16.0-16-ge6a35c8+7/python/lsst/pipe/base/cmdLineTask.py", line 388, in __call__
    result = self.runTask(task, dataRef, kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/pipe_base/16.0-16-ge6a35c8+7/python/lsst/pipe/base/cmdLineTask.py", line 447, in runTask
    return task.runDataRef(dataRef, **kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/pipe_base/16.0-16-ge6a35c8+7/python/lsst/pipe/base/timer.py", line 149, in wrapper
    res = func(self, *args, **keyArgs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/cp_pipe/16.0-4-gade8416+10/python/lsst/cp/pipe/makeBrighterFatterKernel.py", line 448, in runDataRef
    exp1 = self.isr.runDataRef(dataRef).exposure
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/pipe_base/16.0-16-ge6a35c8+7/python/lsst/pipe/base/timer.py", line 149, in wrapper
    res = func(self, *args, **keyArgs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/ip_isr/16.0-14-g6c7ed55+17/python/lsst/ip/isr/isrTask.py", line 675, in runDataRef
    isrData = self.readIsrData(sensorRef, ccdExposure)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/ip_isr/16.0-14-g6c7ed55+17/python/lsst/ip/isr/isrTask.py", line 435, in readIsrData
    linearizer = dataRef.get("linearizer", immediate=True) if self.doLinearize(ccd) else None
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/daf_persistence/16.0-13-g7649090/python/lsst/daf/persistence/butlerSubset.py", line 198, in get
    return self.butlerSubset.butler.get(datasetType, self.dataId, **rest)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/daf_persistence/16.0-13-g7649090/python/lsst/daf/persistence/butler.py", line 1374, in get
    location = self._locate(datasetType, dataId, write=False)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/daf_persistence/16.0-13-g7649090/python/lsst/daf/persistence/butler.py", line 1293, in _locate
    location = repoData.repo.map(datasetType, dataId, write=write)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/daf_persistence/16.0-13-g7649090/python/lsst/daf/persistence/repository.py", line 242, in map
    loc = self._mapper.map(*args, **kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/daf_persistence/16.0-13-g7649090/python/lsst/daf/persistence/mapper.py", line 165, in map
    func = getattr(self, 'map_' + datasetType)
AttributeError: 'ImsimMapper' object has no attribute 'map_linearizer'
`
I dropped the doLinearize config and then there are different errors:
`makeBrighterFatterKernel FATAL: Failed on dataId={'detector': 3, 'raftName': 'R01', 'detectorName': 'S10', 'visit': 161899}: RuntimeError: No defects available for dataId=DataId(initialdata={'detector': 3, 'raftName': 'R01', 'detectorName': 'S10', 'visit': 161899}, tag=set())
Traceback (most recent call last):
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/pipe_base/16.0-16-ge6a35c8+7/python/lsst/pipe/base/cmdLineTask.py", line 388, in __call__
    result = self.runTask(task, dataRef, kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/pipe_base/16.0-16-ge6a35c8+7/python/lsst/pipe/base/cmdLineTask.py", line 447, in runTask
    return task.runDataRef(dataRef, **kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/pipe_base/16.0-16-ge6a35c8+7/python/lsst/pipe/base/timer.py", line 149, in wrapper
    res = func(self, *args, **keyArgs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/cp_pipe/16.0-4-gade8416+10/python/lsst/cp/pipe/makeBrighterFatterKernel.py", line 448, in runDataRef
    exp1 = self.isr.runDataRef(dataRef).exposure
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/pipe_base/16.0-16-ge6a35c8+7/python/lsst/pipe/base/timer.py", line 149, in wrapper
    res = func(self, *args, **keyArgs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/ip_isr/16.0-14-g6c7ed55+17/python/lsst/ip/isr/isrTask.py", line 675, in runDataRef
    isrData = self.readIsrData(sensorRef, ccdExposure)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/ip_isr/16.0-14-g6c7ed55+17/python/lsst/ip/isr/isrTask.py", line 441, in readIsrData
    defectList = dataRef.get("defects") if self.config.doDefect else None
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/daf_persistence/16.0-13-g7649090/python/lsst/daf/persistence/butlerSubset.py", line 198, in get
    return self.butlerSubset.butler.get(datasetType, self.dataId, **rest)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/daf_persistence/16.0-13-g7649090/python/lsst/daf/persistence/butler.py", line 1374, in get
    location = self._locate(datasetType, dataId, write=False)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/daf_persistence/16.0-13-g7649090/python/lsst/daf/persistence/butler.py", line 1293, in _locate
    location = repoData.repo.map(datasetType, dataId, write=write)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/daf_persistence/16.0-13-g7649090/python/lsst/daf/persistence/repository.py", line 242, in map
    loc = self._mapper.map(*args, **kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/daf_persistence/16.0-13-g7649090/python/lsst/daf/persistence/mapper.py", line 166, in map
    return func(self.validate(dataId), write)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/obs_base/16.0-24-gc1c7f52+10/python/lsst/obs/base/cameraMapper.py", line 698, in map_defects
    raise RuntimeError("No defects available for dataId=%s" % (dataId,))
RuntimeError: No defects available for dataId=DataId(initialdata={'detector': 3, 'raftName': 'R01', 'detectorName': 'S10', 'visit': 161899}, tag=set())
`
Is this indicative of a deficiency in the calibration data or should I be running this differently?

**Comment by wmwv** [comment]
@heather999 I suggest you turn off `isr.doDefect` (and `isr.doLinearize`) on the command line.

What do you get if you run:
```
STACKCVMFS/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/cp_pipe/16.0-4-gade8416+10/bin/makeBrighterFatterKernel.py "${LSSTCAM_REPO_DIR}" --rerun test --id detector=0..3 --visit-pairs 161899,161900 -c xcorrCheckRejectLevel=2 doCalcGains=False isr.doDark=True isr.doBias=True isr.doCrosstalk=True isr.doDefect=False isr.doLinearize=False --clobber-config --clobber-versions
```

**Comment by heather999** [comment]
Link to Slack discussion: https://lsstc.slack.com/archives/C978LTJGN/p1551226370049600

**Comment by heather999** [comment]
Looking better
```
root INFO: Running: /cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_49/stack/miniconda3-4.5.4-fcd27eb/Linux64/cp_pipe/16.0-4-gade8416+10/bin/makeBrighterFatterKernel.py imsim_repo --rerun test --id detector=0..3 --visit-pairs 161899,161900 -c xcorrCheckRejectLevel=2 doCalcGains=False isr.doDark=True isr.doBias=True isr.doCrosstalk=True isr.doDefect=False isr.doLinearize=False --clobber-config --clobber-versions                                                                                                                                                         
makeBrighterFatterKernel WARN: Found config.isr.doDefect set to False for brighter-fatter kernel calulation. It is probably desirable to have this set to True                                
makeBrighterFatterKernel WARN: Found config.isr.doLinearize set to False for brighter-fatter kernel calulation. It is probably desirable to have this set to True                             
makeBrighterFatterKernel WARN: Found config.isr.doDefect set to False for brighter-fatter kernel calulation. It is probably desirable to have this set to True                                
makeBrighterFatterKernel WARN: Found config.isr.doLinearize set to False for brighter-fatter kernel calulation. It is probably desirable to have this set to True                             
makeBrighterFatterKernel INFO: Retrieved stored gain for detector 0                                                                                                                           
makeBrighterFatterKernel.isr INFO: Performing ISR on sensor {'detector': 0, 'raftName': 'R01', 'detectorName': 'S00', 'visit': 161899}                                                        
LsstCamMapper WARN: amp.getRawBBox() != data.getBBox(); patching. ((minimum=(0, 0), maximum=(543, 2047)) v. (minimum=(0, 0), maximum=(531, 2019)))                                            
WARNING: ErfaWarning: ERFA function "dtf2d" yielded 1 of "dubious year (Note 6)" [astropy._erfa.core]                                                                                         
WARNING: ErfaWarning: ERFA function "utctai" yielded 1 of "dubious year (Note 3)" [astropy._erfa.core]                                                                                        
makeBrighterFatterKernel.isr.crosstalk INFO: Applying crosstalk correction                                                                                                                    
makeBrighterFatterKernel.isr INFO: Performing ISR on sensor {'detector': 0, 'raftName': 'R01', 'detectorName': 'S00', 'visit': 161900}
WARNING: ErfaWarning: ERFA function "dtf2d" yielded 1 of "dubious year (Note 6)" [astropy._erfa.core]
makeBrighterFatterKernel.isr.crosstalk INFO: Applying crosstalk correction
makeBrighterFatterKernel INFO: Preparing images for cross-correlation calculation for detector 0
makeBrighterFatterKernel INFO: Generating kernel(s) for 0
makeBrighterFatterKernel INFO: Success: SuccessiveOverRelaxation converged in 121 iterations.
outError: 2.013653328023057e-19, inError: 2.0541948804862e-19
makeBrighterFatterKernel INFO: Finished generating kernel(s) for 0
makeBrighterFatterKernel WARN: Found config.isr.doDefect set to False for brighter-fatter kernel calulation. It is probably desirable to have this set to True
makeBrighterFatterKernel WARN: Found config.isr.doLinearize set to False for brighter-fatter kernel calulation. It is probably desirable to have this set to True
makeBrighterFatterKernel INFO: Retrieved stored gain for detector 1
makeBrighterFatterKernel.isr INFO: Performing ISR on sensor {'detector': 1, 'raftName': 'R01', 'detectorName': 'S01', 'visit': 161899}
LsstCamMapper WARN: amp.getRawBBox() != data.getBBox(); patching. ((minimum=(0, 0), maximum=(543, 2047)) v. (minimum=(0, 0), maximum=(531, 2019)))
makeBrighterFatterKernel.isr.crosstalk INFO: Applying crosstalk correction
makeBrighterFatterKernel.isr INFO: Performing ISR on sensor {'detector': 1, 'raftName': 'R01', 'detectorName': 'S01', 'visit': 161900}
makeBrighterFatterKernel.isr.crosstalk INFO: Applying crosstalk correction
makeBrighterFatterKernel INFO: Preparing images for cross-correlation calculation for detector 1
makeBrighterFatterKernel INFO: Generating kernel(s) for 1
makeBrighterFatterKernel INFO: Success: SuccessiveOverRelaxation converged in 121 iterations.
outError: 1.9362230188334995e-19, inError: 2.1829087262009317e-19
makeBrighterFatterKernel INFO: Finished generating kernel(s) for 1
makeBrighterFatterKernel WARN: Found config.isr.doDefect set to False for brighter-fatter kernel calulation. It is probably desirable to have this set to True
makeBrighterFatterKernel WARN: Found config.isr.doLinearize set to False for brighter-fatter kernel calulation. It is probably desirable to have this set to True
makeBrighterFatterKernel INFO: Retrieved stored gain for detector 2
makeBrighterFatterKernel.isr INFO: Performing ISR on sensor {'detector': 2, 'raftName': 'R01', 'detectorName': 'S02', 'visit': 161899}
LsstCamMapper WARN: amp.getRawBBox() != data.getBBox(); patching. ((minimum=(0, 0), maximum=(543, 2047)) v. (minimum=(0, 0), maximum=(531, 2019)))
makeBrighterFatterKernel.isr.crosstalk INFO: Applying crosstalk correction
makeBrighterFatterKernel.isr INFO: Performing ISR on sensor {'detector': 2, 'raftName': 'R01', 'detectorName': 'S02', 'visit': 161900}
makeBrighterFatterKernel.isr.crosstalk INFO: Applying crosstalk correction
makeBrighterFatterKernel INFO: Preparing images for cross-correlation calculation for detector 2
makeBrighterFatterKernel INFO: Generating kernel(s) for 2
makeBrighterFatterKernel INFO: Success: SuccessiveOverRelaxation converged in 119 iterations.
outError: 2.228153927061187e-19, inError: 2.302335377887706e-19
makeBrighterFatterKernel INFO: Finished generating kernel(s) for 2
makeBrighterFatterKernel WARN: Found config.isr.doDefect set to False for brighter-fatter kernel calulation. It is probably desirable to have this set to True
makeBrighterFatterKernel WARN: Found config.isr.doLinearize set to False for brighter-fatter kernel calulation. It is probably desirable to have this set to True
makeBrighterFatterKernel INFO: Retrieved stored gain for detector 3
makeBrighterFatterKernel.isr INFO: Performing ISR on sensor {'detector': 3, 'raftName': 'R01', 'detectorName': 'S10', 'visit': 161899}
LsstCamMapper WARN: amp.getRawBBox() != data.getBBox(); patching. ((minimum=(0, 0), maximum=(543, 2047)) v. (minimum=(0, 0), maximum=(531, 2019)))
makeBrighterFatterKernel.isr.crosstalk INFO: Applying crosstalk correction
makeBrighterFatterKernel.isr INFO: Performing ISR on sensor {'detector': 3, 'raftName': 'R01', 'detectorName': 'S10', 'visit': 161900}
makeBrighterFatterKernel.isr.crosstalk INFO: Applying crosstalk correction
makeBrighterFatterKernel INFO: Preparing images for cross-correlation calculation for detector 3
makeBrighterFatterKernel INFO: Generating kernel(s) for 3
makeBrighterFatterKernel INFO: Success: SuccessiveOverRelaxation converged in 125 iterations.
outError: 1.8302156874317663e-19, inError: 2.0335290619359147e-19
makeBrighterFatterKernel INFO: Finished generating kernel(s) for 3
```

**Comment by TomGlanzman** [comment]
To move beyond "blinding running" the Michael/Jim brighter-fatter scripts (which are successfully running on cori-haswell), an initial set of newbie questions has arisen.  From a conversation with Jim last week, my understanding includes that we need to generate BF kernels, one per sensor (rather than one per amplifier -- which appears to be an option).

1. We appear to have flat pairs available for testing but only for four sensors.  Between Jim and Michael, both imsim and phosim were used to generate flats.  Many more are needed.  Which tool should be used and in what configuration?  Maybe this is already documented somewhere?

2. Do we need kernels generated for all six bands and, hence, flats for all six bands?

3. How many flat pairs per BF kernel should be used? 

4. "export OMP_NUM_THREADS=2" is defined in the script(s).  Does this have any effect?  Does the makeBrighterFatterKernel script truly have multi-threading capability?

5. Are gains and PTC data also needed (they appear to exist in the various test directories that Heather collected together) and, if so, is the data in these test directories sufficient or, if not, where might I find them?

6. What sort of (automated) validation, if any, would be good to run on the results?

7. A small puzzlement in looking through the various test directories: for some flats phoSim appears to have been used, but with an instance catalog that contains stars and galaxies.  Maybe they were simply outside the field of view for the sensors being simulated?  And related to that, the test scripts make certain that reference catalogs are available.  Are these really needed?  Were these defined to short-circuit some of the required processing needed by the makeBrighterFatterKernel task?

  Thanks, Tom

**Comment by TomGlanzman** [comment]
Time for an update.  Over the past couple of weeks, most of the above questions (along with some new ones) got answered.  

- As of last Friday, Heather has produced a set of brighter-fatter flats (4 pairs of flats for each of 5 flux levels).
- BF kernels will be generated for only the i-band (until someone decides differently)
- Kernel generation will use all (20) flat pairs in one go
- BF gains will be calculated (or mocked up) 
- The DM repo used in this exercise was constructed manually and piecemeal which seems to work, but it has been recommended that a single, production repo be used.
- A working script has run successfully (mechanically) using all bf flats on five sensors (actually, the test is still running at this moment)
- The kernels so produced need to be validated prior to processing the entire focal plane.
- Initially, plan to produce the kernels manually (rather than using Parsl) to save time.   A subsequent step will be to Parslize the workflow

Output results of these initial tests (will) appear here at NERSC:

/global/cscratch1/sd/descdm/tomTest/bf_repo/rerun/test<N>/calibrations

**Comment by TomGlanzman** [comment]
A full set of BF kernels has been produced and are ready for validation.
/global/cscratch1/sd/descdm/tomTest/bfKernels

**Comment by TomGlanzman** [comment]
A second set of kernels, using Craig Lage's latest (and untagged) BF code has been produced and stored here:
/global/cscratch1/sd/descdm/tomTest/bfKernels.2

**Comment by johannct** [comment]
@jchiang87 Does this still need to be kept open? Feel free to close it if not.

**Comment by TomGlanzman** [comment]
I'd like to keep this open until a full Parsl pipeline has been run successfully and acceptably.

**Comment by johannct** [comment]
@TomGlanzman I believe the parsl pipeline has been completed. Where does it live? Can this issue be closed?

**Comment by TomGlanzman** [comment]
@johannct A prototype Parsl workflow to generate brighter-fatter kernels was advanced to the stage where it functioned, but not necessarily efficiently.  I was diverted onto the singleFrameDriver work in early July so this project was paused, quite possibly with various loose ends.  Since that time, I've taken the lessons learned and applied them to sfd which itself advanced.  So yes, this issue may be closed with the proviso that the Parsl workflow will need some updating/tuning to achieve production status.

The current development is here in my private repo until it is sufficiently developed to promote:
https://github.com/TomGlanzman/genBrighterFatter
