### ISSUE TITLE
Request DataTransfer of Run1.2p raw files from IN2P3 to NERSC

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#85]
Hi @airnandez @boutigny @johannct 
We lost our copy of the Run1.2p raw files at NERSC to a purge of scratch.  While we could regenerate them from the original phosim output, we would like to get a copy from IN2P3.  I believe this data is stored in:
`/sps/lsst/datasets/desc/DC2/Run1.2p-newformat`
which was ingested back in August: http://srs.slac.stanford.edu/Pipeline-II/exp/LSST-DESC/log.jsp?pi=52323734
@johannct can you confirm that this is the most recent copy of the raw Run1.2p data?  And if so, @airnandez could you set up a data transfer back to NERSC into the `/global/projecta/projectdirs/global/in2p3` area?

**Comment by airnandez** [comment]
@heather999 Could you confirm you meant the destination directory at NERSC to be `/global/projecta/projectdirs/lsst/global/in2p3`? The one that you mention (i.e. `/global/projecta/projectdirs/global/in2p3`)  does not exist.

This is the current contents of the directory `/sps/lsst/datasets/desc/DC2/Run1.2p-newformat` at CC-IN2P3:

```
$ tree -L 1 /sps/lsst/datasets/desc/DC2/Run1.2p-newformat
/sps/lsst/datasets/desc/DC2/Run1.2p-newformat
├── CALIB
├── calib_raw
├── DC2-R1-2p-uDDF-g
├── DC2-R1-2p-uDDF-i
├── DC2-R1-2p-uDDF-r
├── DC2-R1-2p-uDDF-u
├── DC2-R1-2p-uDDF-y
├── DC2-R1-2p-uDDF-z
├── DC2-R1-2p-WFD-g
├── DC2-R1-2p-WFD-i
├── DC2-R1-2p-WFD-r
├── DC2-R1-2p-WFD-u
├── DC2-R1-2p-WFD-y
├── DC2-R1-2p-WFD-z
└── logs

15 directories, 0 files
```

Could you please confirm what of those subdirectories' contents you would like to be transferred to NERSC?

I wait for your confirmation and @johannct 's before triggering this campaign.

**Comment by heather999** [comment]
@airnandez Yes sorry, this is likely the best destination: `/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p`  so that the data is transferred alongside the other Run1.2p data.

**Comment by airnandez** [comment]
Do you need we transfer to NERSC all the subdirectories currently under `/sps/lsst/datasets/desc/DC2/Run1.2p-newformat`?

**Comment by airnandez** [comment]
The data under `/sps/lsst/datasets/desc/DC2/Run1.2p-newformat` at CC-IN2P3 is copied at NERSC under `/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p-newformat`. Total volume: 5.6 TB.
