### ISSUE TITLE
Describe how to do forced photometry on DIAObjects

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#9]
_From @drphilmarshall on January 18, 2018 23:20_

The missing piece from Twinkles, now needs writing down in the Cookbook.

_Copied from original issue: LSSTDESC/DC2_Repo#93_

**Comment by drphilmarshall** [comment]
@SimonKrughoff @DominiqueFouchez  I saw a mention in the Slack channel of a chart showing which parts of the DM DIA pipeline were not yet available - do you have that to hand? I'm wondering if forced photometry is one of them... Thanks!

**Comment by SimonKrughoff** [comment]
I don't have it right on hand, but the story was that I was worried about association.  I'm not really anymore since we are focusing on DRP style DIAObjects.  Forced photometry should be straightforward, but we may need to write a wrapper script that takes the correct objects to seed it.

**Comment by SimonKrughoff** [comment]
I think the process you say is a good approximation of how we will do things in operations.  I don't know if anyone is thinking about the forced photometry part yet.  I can check around.

It would be wonderful if we could write that script and issue a PR on `pipe_tasks` or `ip_diffim`.

**Comment by drphilmarshall** [comment]
I know, right? I long for a DESC-written DM-accepted Stack pull request. It
would somehow show that we had arrived :-)

**Comment by rbiswas4** [comment]
>  I saw a mention in the Slack channel of a chart showing which parts of the DM DIA pipeline were not yet available.

Is such a chart available somewhere ? That would be very useful to be able to see.

**Comment by SimonKrughoff** [comment]
[Here](https://jira.lsstcorp.org/browse/DM-13375) is some discussion DIAObjects in the DPDD.
