### ISSUE TITLE
Investigate visit 254378 failures in 2.1i preliminary tests

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/ImageProcessingPipelines#95]
Following a preliminary run of singleFrameDriver on the CC batch of simulated visits (with the exceedingly good PSF), it appeared that it would be healthier to have a larger reference catalogue to avoid failures on the edges. Still visit 254378 has crashes that need investigation (it may not be the only one)

**Comment by boutigny** [comment]
The remaining failures in visit 254378 are all related to the aperture correction measurement for `modelfit_CModel_dev`
After discussion with Lauren, I have been able to recover 2 of the failures (I didn't try for the others) by adding a maxSN cut on `measurePsf.starSelector["objectSize"]`
The configuration parameters are the following:
```
config.charImage.measurePsf.starSelector["objectSize"].doFluxLimit = False
config.charImage.measurePsf.starSelector["objectSize"].doSignalToNoiseLimit = True
config.charImage.measurePsf.starSelector["objectSize"].signalToNoiseMin = 20
config.charImage.measurePsf.starSelector["objectSize"].signalToNoiseMax = 200
```
We now need to run more extensive tests to check whether this configuration is working for other visits, especially those with a standard PSF size.

**Comment by johannct** [comment]
Running with Lauren defaults for the current 6mths and a larger ref cat, so we can close this.
