### ISSUE TITLE
Processing y1-y2-wfd

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/ImageProcessingPipelines#97]
859538 sensors
w19 with dc2/run2.1 branches of obs_lsst, meas_extensions_ngmix
Still expect some twiddling of parameters.

**Comment by johannct** [comment]
INGEST : 5000 sensor batch which corresponds to ~ 200 parallel jobs of 8 cores each, our current allocation (1600 cores)

**Comment by johannct** [comment]
Starting from scratch : 6mths data as a testbed. QA visitAnalysis.py from pipe_analysis added to the pipeline.

**Comment by johannct** [comment]
The "grizyu" trick to avoid the version conflict did not seem to work this time, so I added `--clobber-config` for the u-band.

**Comment by heather999** [comment]
This comes back to the fact that we could handle u-band in a separate rerun from grizy - right?  That would avoid the need for `--clobber-config`.  Not something we have to do immediately but I think to handle the configs correctly and to make sure we have the correct record of the configs used, we should handle u separately.

**Comment by johannct** [comment]
It complicated matter significantly for the pipeline

**Comment by heather999** [comment]
I thought we had a recipe for combining two reruns so that they could be used as input to the next step in processing - such as `multiband` in this case?  Wasn't there Eli's suggestion - or did that not work?
https://lsstc.slack.com/archives/C2K97E3L5/p1544635024028200

**Comment by johannct** [comment]
How to implement that in the pipeline, which uses the rerun params globally? Furthermore you still need top merge. Plus I do not think that coadd-u:coadd-grizy:multiband will make it so that multiband look at coadd-u and coadd-grizy to gather everything so indeed the merge has to be "manual". And that will complicate the management of the rerun names, which currently are only two. So I do not see it as straightforward, but I certainly will take any example of a proof of principle and try to code it in.

**Comment by johannct** [comment]
I opened https://github.com/LSSTDESC/ImageProcessingPipelines/issues/105 capturing Eli's trick. The problem is that I have to run it between each coaddDriver and multibandDriver process, as now they are sequenced for a given tract and patch set....

**Comment by johannct** [comment]
According to `ls -lR rerun/coadd-v1/deepCoadd-results/merged/ | grep "^d" | wc -l` there are 6545 patches in the 6mths production. Only 1401 files mcalmax-deblended-*.fits have been produced. I see the following traces in the log :
```
processDeblendedCoaddsMetacalMax FATAL: Failed on dataIds=[DataId(initialdata={'tract': 4230, 'patch': '4,6', 'filter': 'i'}, tag=set()), DataId(initialdata={'tract': 4230, 'patch': '4,6', 'filter': 'z'}, tag=set())]: KeyError: 'r'
Traceback (most recent call last):
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_base/17.0.1-2-g3e5d191+31/python/lsst/pipe/base/cmdLineTask.py", line 388, in __call__
    result = self.runTask(task, dataRef, kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_base/17.0.1-2-g3e5d191+31/python/lsst/pipe/base/cmdLineTask.py", line 447, in runTask
    return task.runDataRef(dataRef, **kwargs)
  File "/pbs/throng/lsst/software/desc/DC2/Run2.1i/v1/meas_extensions_ngmix/python/lsst/meas/extensions/ngmix/processCoaddsTogether.py", line 160, in runDataRef
    results = self.run(images, ref, imageId=imageId, replacers=replacers)
  File "/pbs/throng/lsst/software/desc/DC2/Run2.1i/v1/meas_extensions_ngmix/python/lsst/meas/extensions/ngmix/processCoaddsNGMix.py", line 1211, in run
    images, ref, replacers, imageId,
  File "/pbs/throng/lsst/software/desc/DC2/Run2.1i/v1/meas_extensions_ngmix/python/lsst/meas/extensions/ngmix/processCoaddsNGMix.py", line 153, in run
    extractor = self._get_extractor(images)
  File "/pbs/throng/lsst/software/desc/DC2/Run2.1i/v1/meas_extensions_ngmix/python/lsst/meas/extensions/ngmix/processCoaddsNGMix.py", line 360, in _get_extractor
    return MBObsExtractor(self.cdict, images)
  File "/pbs/throng/lsst/software/desc/DC2/Run2.1i/v1/meas_extensions_ngmix/python/lsst/meas/extensions/ngmix/mbobs_extractor.py", line 38, in __init__
    self._verify()
  File "/pbs/throng/lsst/software/desc/DC2/Run2.1i/v1/meas_extensions_ngmix/python/lsst/meas/extensions/ngmix/mbobs_extractor.py", line 315, in _verify
    imf = self.images[filt]
KeyError: 'r'
```

**Comment by johannct** [comment]
addendum : the 6mths 441 visits distribute as follows : 36 u, 10 g, 44 r, 24 i, 180 z, 147 y, so it looks fairly unbalanced. Did I make a mistake in selecting the first six months?

**Comment by jchiang87** [comment]
The problem is that the `y1-y2-wfd` data (see https://github.com/LSSTDESC/ImageProcessingPipelines/issues/86#issuecomment-493650869) are not complete for the earliest epochs.  These are the "batch 2" data (simulated with the larger PSF) and the earliest visits in that batch are the ones that were leftover from batch 1 (which had the small PSF).   Since these are the stragglers, selecting the first six months will have lots of gaps.  Also note that the total number of DC2 WFD visits is ~50k, so we'd expect roughly ~2500 visits in the first six months, and the 441 is less than 20% of the expected depth.   Here's a plot of band vs MJD for the visits in the `y1-y2-wfd` dataset:
![y1-y2-wfd_visits](https://user-images.githubusercontent.com/1994473/58740624-3d7ee380-83c6-11e9-8211-d0a84df10a13.png)
To the left of the dashed line are the 441 visits.

If we want reasonably well-distributed coverage in all bands, we should either fill out the sparser bands with later visits or pick a 6 month interval to the right of the line that also avoids the seasons where LSST isn't observing in the DC2 WFD region.

**Comment by johannct** [comment]
`sqlite3` registry.sqlite3 "select distinct visit from raw where date < \"2024-01-03T01:19:03.326\" and date > \"2023-07-03T01:19:03.326\" order by date(date);"` will provide 2888 visits, much more in line with what is expected; These would be the last semester of y2, as the latest visit has date `2023-12-31T06:55:22.651`

**Comment by johannct** [comment]
@jchiang87 is the g coverage in your plot something expected and harmless? It seems barely deeper than u band....

**Comment by jchiang87** [comment]
It's expected.  Here's a plot of the cumulative number of the minion_1016 visits versus MJD for each band:
![filters_vs_mjd](https://user-images.githubusercontent.com/1994473/58749671-b0777100-843d-11e9-81f3-c1224a35e03a.png)

**Comment by jchiang87** [comment]
fwiw, here are plots of visit depth across the WFD region for the original 6 month selection (`date < "2022-07-03T01:19:03.326"`):
![y1-y2-wfd_6months](https://user-images.githubusercontent.com/1994473/58811201-39281580-85d4-11e9-8a9e-ab9f7bc9a508.png)
I'll post a similar plot for the revised 6 month selection (`date < \"2024-01-03T01:19:03.326\" and date > \"2023-07-03T01:19:03.326\"`) shortly.

**Comment by jchiang87** [comment]
Here are the visit depth plots for the revised selection (`date < \"2024-01-03T01:19:03.326\" and date > \"2023-07-03T01:19:03.326\"`):
![y2_6month_visit_depth](https://user-images.githubusercontent.com/1994473/58813559-dc7b2980-85d8-11e9-9aff-208feea247b6.png)

**Comment by johannct** [comment]
Thanks @jchiang87 so I presume that this serves as a confirmation that this 6mth subset will be fine

**Comment by jchiang87** [comment]
Yes, I think that's correct. (The missing corner arises because of the un-simulated visits that intersect the DDF region.)

**Comment by johannct** [comment]
Starting dr1b-v1 : 2888 visits (y2 sem 2), 173 patches, 7239 patches

**Comment by johannct** [comment]
multibandDriver resulted in 12 jobs crashing, with 3 different types of crash : 
- https://github.com/LSSTDESC/ImageProcessingPipelines/issues/112
- https://github.com/LSSTDESC/ImageProcessingPipelines/issues/113
- https://github.com/LSSTDESC/ImageProcessingPipelines/issues/114

coaddDriver resulted in 12 jobs crashing as well, all with the following crash : 
- https://github.com/LSSTDESC/ImageProcessingPipelines/issues/115

**Comment by johannct** [comment]
I checked in two multiBand cases and there is no match with the tract/patch/filter crashes in coaddDriver

**Comment by johannct** [comment]
staged to archive.
