### ISSUE TITLE
Bad outdir for merge_cat dpdd stage, as it is not in a natural transferable directory

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/ImageProcessingPipelines#98]
https://github.com/LSSTDESC/ImageProcessingPipelines/blob/971c12cf474e471535519eecea659ea1ad07710a/workflows/srs/pipe_setups/run_dpdd#L5

**Comment by wmwv** [comment]
The DPDD products will always and should be assembled outside of the data repo path.
Would it be appropriate to add ${WORKDIR}/dpdd to the transfer scripts, or is the problem that WORKDIR isn't a centrally-defined location?

**Comment by johannct** [comment]
This is a purely pipeline related issue : the path is inappropriate in the context of straightforward transferring. I will propose another final path for these products, for instance rerun/<rerun2>-dpdd where <rerun2> is the second rerun param, coadd-v2 in the current prod.

**Comment by wmwv** [comment]
My point was that it's not natural to put these products under the `rerun` directory in the Butler repository.  In principle the Butler should be seen to be the controller of everything in and below the repository path.

**Comment by johannct** [comment]
Agreed, but the rerun naming scheme also defines a prod, so I am not sure about been orthodox here

**Comment by wmwv** [comment]
For example, on NERSC we're arranging them as:

DPDD products:
`/global/projecta/projectdirs/lsst/production/DC2_ImSim/Run1.2i/dpdd`

The DM Science Pipelines processing Butler repo:
`/global/projecta/projectdirs/lsst/production/DC2_ImSim/Run1.2i/desc_dm_drp/w_2018_39`

**Comment by wmwv** [comment]
I hear you that multiple reprocessings of data, e.g., `rerun/coadd-v4` should have different subdirectories in `dpdd`, e.g., `dpdd/coadd-v4`.  For the Run 1.x series each reprocessing was generally better so we presented just one main `dpdd` version.

For Run 2.x I can imagine two different proceedings that we want to serve, e.g., with different sky-background procedures.  I agree with using a consistent name, but it could still be under a different directory.

Eventually we may be able to produce the DPDD products directly from the LSST DM Science Pipelines.  At this point using the Butler to write such products might make sense and they would then go in the Butler-controlled repository.

**Comment by johannct** [comment]
opting for ${OUT_DIR}/dpdd/${RERUN}/object_table_summary/ and likewise ${OUT_DIR}/dpdd/${RERUN}/source_table_summary for the forced source table.
5d216c5..6e34403
